### ISSUE TITLE
error in 14.1.0 /geography/RegioIndelingen/Impl/Make_Randstad/geometry

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/RSopen#1]
Ik krijg op:
/geography/RegioIndelingen/Impl/Make_Randstad/geometry

een error in 14.1.0 maar niet in 13.4.0.

Ik zou erbij zetten met welke exe RSopen gedraaid dient te worden

Failure during Reading from storage
[/ExportSettings/metainfo/Contents/Svn/RevisionInfo ](dms:dp.general:/ExportSettings/metainfo/Contents/Svn/RevisionInfo)

Context:
Thread 5
1. while in TreeItem::ReadItem( /ExportSettings/metainfo/Contents/Svn/RevisionInfo: AbstrDataItem )

**Comment by basvanbemmel** [comment]
Ook op /WriteBasedata/Generate_Run1 overigens in de GUI

**Comment by jipclaassens** [comment]
Ah nu we op github zitten is er geen SVn versie bestand meer. We moeten dan even de SVn containers uit de exportsettimgs container weggooien. 

Ik ga nog kijken of ik een github hash hier kan gaan gebruiken.

**Comment by basvanbemmel** [comment]
ik vermoed dat het te maken heeft met het svn-deel in ExportSettings.dms
maar dat is voor svn bedoeld, aangezien dit een git-versie is zou ik het eruit halen..

**Comment by basvanbemmel** [comment]
Opgelost in:
c1222bb5f28de7548114c6239524996375689a2a

**Comment by basvanbemmel** [comment]
Ik heb het al opgelost, zie laatste commit/push op github

Groet
Bas

Verstuurd vanaf mijn iPhone

Op 21 sep. 2023 om 07:05 heeft Jip Claassens ***@***.***> het volgende geschreven:

﻿

Ah nu we op github zitten is er geen SVn versie bestand meer. We moeten dan even de SVn containers uit de exportsettimgs container weggooien.

Ik ga nog kijken of ik een github hash hier kan gaan gebruiken.
