### ISSUE TITLE
Hoe koppelen we de brondata (LGN) klassen aan de model klassen?

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#104]
Nu heb ik het als volgt gedaan, eerst de klassen zoals gestuurd door Janneke. Maar ik heb geen klassen voor de uitgecommentarieerde klassen. Verder heb ik de gg_vee uit PeatyMeadows gehaald. Want deze worden geroteerd gebruikt. 

```
 'appelbomen'                       , '60','243', '69','LGNKlasse/V/boomgaarden'
,'consumptieaardappelen'           ,'176','105',  '9','LGNKlasse/V/Aardappelen'
// ,'gewas beweiden'                   ,'232','153', '25',''
// ,'gras maai'                        ,'232','153', '25',''
// ,'laanbomen'                        ,'232','153', '25',''
,'snijmais'                         ,'229','157', '32','LGNKlasse/V/maïs'
,'suikerbieten'                       ,'227', '24','128','LGNKlasse/V/bieten'
,'tulp'                             ,'172','127','168','LGNKlasse/V/Bloembollen'
,'wintertarwe'                     ,'252','255', '18','LGNKlasse/V/Granen'
,'zaaiuien'                         ,'254',  '0','197','LGNKlasse/V/overige_landbouwgewassen'
// ,'zetmeel aardappelen'              ,'255','255','128','LGNKlasse/V/Aardappelen'

,'agr_gg_vee_extensief'             ,'255','240', '38','VoederCategorie/V/extensive'
,'agr_gg_vee'                       ,'255','223','165','VoederCategorie/V/standard'
,'agr_gg_vee_intensief'             ,'128','128','128','VoederCategorie/V/intensive'
,'natuur_gras'                      , '99','186', '49','VoederCategorie/V/non_dairy_pasture'
```

Rotaties voor gg vee (=melkvee):
- gras met herinzaai
- gras zonder herinzaai
- mais

**Comment by jipclaassens** [comment]
#105

**Comment by jipclaassens** [comment]
**Nu LGN - LandbouwK**
aardappelen - akkerbouw
bieten - akkerbouw
granen - akkerbouw
overige landbouwgewassen - groenteteelt
boomgaarden - fruitteelt
rietvegetatie - rietteelt
boomkwekerijen - boomgaard
fruitkwekerijen - fruitteelt

En MakeDefined(gg_Landbouw_LGN, gg_Landbouw_Voedergewas)

**Comment by BartRijken** [comment]
@jipclaassens  de relatie 'boomkwekerijen - boomgaard' klopt niet. Ik zou het voor nu even zo doen:

Nu LGN - LandbouwK
aardappelen - akkerbouw
bieten - akkerbouw
granen - akkerbouw
overige landbouwgewassen - groenteteelt
**boomgaarden - boomgaard**
rietvegetatie - rietteelt
**boomkwekerijen - ???** (Deze landbouwK voorlopig maar even weghalen, tenzij Diogo ergens een boomkwekerijen klasse heeft (tree nursery?))
fruitkwekerijen - fruitteelt

**Comment by jipclaassens** [comment]
> @jipclaassens de relatie 'boomkwekerijen - boomgaard' klopt niet. Ik zou het voor nu even zo doen:
> 
> Nu LGN - LandbouwK aardappelen - akkerbouw bieten - akkerbouw granen - akkerbouw overige landbouwgewassen - groenteteelt **boomgaarden - boomgaard** rietvegetatie - rietteelt **boomkwekerijen - boomkwekerijen (Dit is de klasse 'tree nursery uit Diogo 2015, zie de tabel in issue #106 )** fruitkwekerijen - fruitteelt

Dus je wilt een nieuw extra modeltype? Je weet dat jij deze klasse zo telefonisch had doorgegeven? ;)

**Comment by jipclaassens** [comment]
### ModelType
Hier wordt de **landgebruiks_rel** voor gg_vee gedefineerd uit de VoederCategorieen.
`/Classifications/Actor/LandbouwK/Elements`

De **landgebruiks_rel** voor de overige klassen obv van LGN worden gedefinieerd hier:
`/Classifications/Grondgebruik/LGNKlasse/elem`

### GewasSoortYR

Hier wordt de relatie tussen de gewassen en de ModelTypen gelegd. En ook welke YieldReduction kaarten mogen worden gebruikt.
`/Classifications/Landbouw/GewasSoortYR/Elements`

NB: maak je een nieuw ModelType dat geen gewas opzichzelf is, dan zul je een extra attribuut moeten toevoegen hier: `/VariantData/Suitability/Y2030/Landbouw/Factoren/YieldReduction/AveragePeriod`

### Suitability
De uitwerking van yield reduction met de transititiekosten, gewas rotaties en economic performance worden allemaal hier gedefinieerd:
`/VariantData/Suitability/Y2030/Landbouw/per_ModelType`

Voeg je een extra gewas/modeltype toe, controleer hier of alles goed gaat.
