### ISSUE TITLE
Check de welke rotatie schema Vasco heeft beschreven en hoe die relateren aan de ModelTypen en LGN

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#106]

**Comment by BartRijken** [comment]
De relatie tussen de rotatie schema's en LGN:

![image](https://github.com/user-attachments/assets/207ee84d-0f88-4a76-beba-410a5495f5cc)

**Comment by BartRijken** [comment]
Zie ook, op regionale schaal (uit zelfde paper van Diogo):

![image](https://github.com/user-attachments/assets/9bd6c68d-b79d-407d-8689-d77fd1ef8586)
