### ISSUE TITLE
vergelijk RS incrementeel met RS-in-1-x-naar-2050

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#11]
Zie trello issue [#663 ](https://trello.com/c/CE2JbI0C/663-vergelijk-rs-incrementeel-met-rs-in-1-x-naar-2050)

Wat is nu de uitkomst?

Edit: zon lijkt te veel te alloceren bij incrementeel. Worden de rest claims wel juist bepaald?

**Comment by basvanbemmel** [comment]
eerst kijken of het uberhaupt runt met 10 jaar ga ik zo aanzetten op een andere VM-machine

**Comment by basvanbemmel** [comment]
![image](https://github.com/ObjectVision/RSopen/assets/24241780/a8aa813c-a6bd-4723-897b-043108bc9c94)

**Comment by basvanbemmel** [comment]
![verschil_RG_HOOG_2050_once_vs_steps](https://github.com/ObjectVision/RSopen/assets/24241780/94ad721b-b59a-4176-b8fa-94bc90f15a49)

Hierbij het verschil van RG 2050 in 1 keer en in stappen. Ruimtelijk beeld klopt aardig met elkaar. Ik begrijp het verschil niet in windturbines. Waarom is dat zoveel lager (1259) indien in 1 keer naar 2050

**Comment by jipclaassens** [comment]
Wat is je instelling qua wind iteraties?

**Comment by basvanbemmel** [comment]
gewoon default zoals op github (933587c62fedd43018f4fd575671031ab2a70c35) aanwezig dus:

	// Aantal iteraties in de allocatie. Iteraties zijn  nodig om niet vervulde restclaims in een iteratie in een volgende iteratie te vervullen
	parameter<uint8> Default_NrOfIters := 10b;
	parameter<uint8> NrOfIters_Wind := Default_NrOfIters; // Alleen relevant als Windpotentie_StempelAan == true
	
	// Beschikbare locaties voor windturbines worden (her)berekend, o.b.v. de zgn. stempelprocedure (true) danwel ingelezen uit eerder berekende bestanden (false).
	parameter<bool> Windpotentie_StempelAan := false; // Indien true wordt de stempel genomen die het meeste aantal windmolen neer zet. Anders wordt het stempel grid met index 0 gepakt
	
	// Aantal sequences in de allocatie. Sequences zijn nodig om verdrongen wooneenheden, banen etc in een sequentie in een volgende sequentie te heralloceren, voor zover de verdringing restclaims opleverede
	parameter<uint8> Default_NrOfSequences := 3b;  //minimaal 2

**Comment by basvanbemmel** [comment]
Kan ook ander vermogen zijn per WT, zou ik moeten kijken

**Comment by jipclaassens** [comment]
Bij direct naar 2050 rekenen wordt wind in 4 stappen gealloceerd: seq0/prov, seq0/NL, seq1/prov, seq2/prov. Met ieder 10 iteraties, met daarin dus 10 verschillende stempel grids.  Dus in 4x10=40 allocatie mogelijkheden.
 
Bij het rekenen in tussenstappen wordt het ook in 4 stappen gealloceerd maar in drie tijdstappen opnieuw. Dus 3x4x10=120 allocatie mogelijkheden.

Mogelijk wordt in bijv 2030 relatief weinig beschikbare ruimte weggekaapt voor wind, die in 2050 wel wordt weggekaapt omdat wind de laatste sector is. Hierdoor kan in 2030 op bepaalde locaties wel wind geplaatst worden die in 2050-direct niet beschikbaar is...

**Comment by basvanbemmel** [comment]
Maar het gaat toch ook om de claim die weggezet moet worden?
Laten we dit issue even op on hold zetten. Voor nu even niet zo belangrijk denk ik.

Ik doe eerst even zelf onderzoek hoeveel vermogen er wordt weggezet

**Comment by basvanbemmel** [comment]
Jip zoekt uit waarom er 3 maal gealloceerd lijkt te worden vanuit de claim
