### ISSUE TITLE
WBS variant WLO integreren in de RV Friesland beleidsscenario's

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#113]

**Comment by jipclaassens** [comment]
@BartRijken als tredes?

**Comment by BartRijken** [comment]
@jipclaassens niet alleen als tredes. Het gata hier om de gehele WBS variant uit WLO: restrcities, plannen, tredes, stimuli, etc. DE grote vraag is hoever PBL (Bas etc) deze variant hebben uitgewerkt: wat de verschillen zijn t.o.v. BaU. Ik vermoed alleen/vooral de restricties voor de stedelijke klassen. check dat eerst even. Daarna deze WBS variant toevoegen aan RSFriesland. Wanneer jij em hebt toegevoegd werk ik em verder uit, in overleg met PBL waar nodig.

**Comment by jipclaassens** [comment]
@BartRijken Ik vermoed nog vrijwel niet. Ik zal het Bas vragen.

**Comment by jipclaassens** [comment]
we kunnen de geleverde wbs kaart gebruiken als aanvullende restrictie kaart. Verder zijn er geen andere plannen/tredes/stimuli. Oftewel er is geen verdere uitwerking van deze variant.
