### ISSUE TITLE
Waterretentiegebieden RVFriesland inlezen

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#115]

**Comment by jipclaassens** [comment]
@BartRijken waar vind ik deze?

**Comment by BartRijken** [comment]
@jipclaassens als het goed is heb je dit ontvangen van Janneke Pouwels of Charlotte van Strien (mijn collega's). Anders nog ff bij hen opvragen. Vraag dan meteen de rest van de invoerdata op voor dit project: bruinrot etc.
