### ISSUE TITLE
Waterretentiegebieden exogeen opleggen als oppervlaktewater en uit admin/allocdomain halen

### ISSUE THREAD

**Issue by BartRijken** [ObjectVision/RSopen#118]
Zie ook #115

**Comment by jipclaassens** [comment]
Bedoel je de 'reservoirs_12.shp' met daarin 'ja' in het veld 'reservoir' ?

Deze dan klassificeren als reeds benut en dus uitsluiten van allocatie?

![image](https://github.com/user-attachments/assets/9aa06a4d-f14f-4c70-821c-4b6c96dd5131)

**Comment by jipclaassens** [comment]
@cvanstrien Zijn deze lokaties echt als reservoirs bedoeld? Want nu zit er een klaverblad van de A7/A32 in, en een aantal dorpen.

![image](https://github.com/user-attachments/assets/f20d60dc-47f0-48ac-b52a-d8adcf7f193f)

**Comment by cvanstrien** [comment]
> @cvanstrien Zijn deze lokaties echt als reservoirs bedoeld? Want nu zit er een klaverblad van de A7/A32 in, en een aantal dorpen.
> 
> ![image](https://private-user-images.githubusercontent.com/48675272/360416204-f20d60dc-47f0-48ac-b52a-d8adcf7f193f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDUxMzgsIm5iZiI6MTcyNDQwNDgzOCwicGF0aCI6Ii80ODY3NTI3Mi8zNjA0MTYyMDQtZjIwZDYwZGMtNDdmMC00OGFjLWI1MmEtZDhhZGNmN2YxOTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA5MjAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhOTAwYmI2Y2Q0MjFjMDc0M2NkYWE5MTA1NDA1ZTY5ODlhNjIyZjg2MmRiNTFhZmYzOGVmNGI4MWNjYzQ5MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QjxgV0SOMhVXjJp6DnqQIMfCKoA_rwnD0QeCLKhZlys)

Ai ja we hebben dit bij de hydrologische modellering (voor ander project) inderdaad zo aangewezen grofweg op basis van ahn en benodigde volume. Ik weet niet hoe ver we in dit project willen inzoomen op deze schaal, maar als we alleen op provincieschaal kijken, zou ik het zo houden. @BartRijken wat denk jij?

**Comment by BartRijken** [comment]
> > @cvanstrien Zijn deze lokaties echt als reservoirs bedoeld? Want nu zit er een klaverblad van de A7/A32 in, en een aantal dorpen.
> > ![image](https://private-user-images.githubusercontent.com/48675272/360416204-f20d60dc-47f0-48ac-b52a-d8adcf7f193f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDUxMzgsIm5iZiI6MTcyNDQwNDgzOCwicGF0aCI6Ii80ODY3NTI3Mi8zNjA0MTYyMDQtZjIwZDYwZGMtNDdmMC00OGFjLWI1MmEtZDhhZGNmN2YxOTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA5MjAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhOTAwYmI2Y2Q0MjFjMDc0M2NkYWE5MTA1NDA1ZTY5ODlhNjIyZjg2MmRiNTFhZmYzOGVmNGI4MWNjYzQ5MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QjxgV0SOMhVXjJp6DnqQIMfCKoA_rwnD0QeCLKhZlys)
> 
> Ai ja we hebben dit bij de hydrologische modellering (voor ander project) inderdaad zo aangewezen grofweg op basis van ahn en benodigde volume. Ik weet niet hoe ver we in dit project willen inzoomen op deze schaal, maar als we alleen op provincieschaal kijken, zou ik het zo houden. @BartRijken wat denk jij?

@cvanstrien en @jipclaassens voor integrake RuimteScanner toepassingen zoals deze is het belangrijk dat de het lokaal een beetje klopt. De retentiegebieden mogen dus niet (teveel) overlappen met bijv. woningen, zoals nu het geval is, want dan gaat het model die woningen slopen en dat kunnen we niet uitleggen. @jipclaassens  graag dus in ieder gevalk even alle gridcellen met infra en verblijfsobjecten (basisjaar) uit de retentiegebieden knippen alvorens deze exogeen op te leggen.

**Comment by jipclaassens** [comment]
![Image](https://github.com/user-attachments/assets/e2cb45c4-fae5-4ce1-b145-52b45d7b0f78)
