### ISSUE TITLE
Is het handig om zowel een label als een project 'RVFriesland' te hebben, zoals in dit issue

### ISSUE THREAD

**Issue by BartRijken** [ObjectVision/RSopen#119]

**Comment by jipclaassens** [comment]
Alle issues komen sws in de volledige issue lijst van RSo. Hierin het handig om onderscheid te maken met reguliere RSo issue door een label eraan te hangen. Het project 'To Do RV-Friesland' kunnen we gebruiken om prioritering hieraan te hangen.

**Comment by BartRijken** [comment]
> Alle issues komen sws in de volledige issue lijst van RSo. Hierin het handig om onderscheid te maken met reguliere RSo issue door een label eraan te hangen. Het project 'To Do RV-Friesland' kunnen we gebruiken om prioritering hieraan te hangen.

Ok het is dus handiog om zowel het label als het project te handhaven?
