### ISSUE TITLE
Uitzoeken hoe we verzilting mee kunnen nemen in de geschiktheidskaarten voor landbouw (in RuimteScanner)

### ISSUE THREAD

**Issue by BartRijken** [ObjectVision/RSopen#121]
- [ ] Welke bronnen zijn beschikbaar?
- [ ] Sluiten ze aan op de peilen uit LN2050?
- [ ] Welke landbouwklassen worden onderscheiden, if any?
- [ ] Hoe kunenn we ze in de geschiktheidskaarten meenemen (euro's, risico's, boolean)?

**Comment by jipclaassens** [comment]
Voorstel: boolean TeveelVerzilting kaart vermenigvuldingen met YR-kaart, zodat suitability naar 0 gaat.
Of iets daartussen in?

@BartRijken werk dit eerst even uit.

**Comment by jipclaassens** [comment]
Verzilitingskaarten zijn ingebouwd. Nu moeten we bedenken hoe we het toepassen. Blocked omdat jij dit nog zou uitdenken. @BartRijken

**Comment by jipclaassens** [comment]
![image](https://github.com/user-attachments/assets/80f4129a-1e8f-45c9-a8d9-0fdcace9cb02)
