### ISSUE TITLE
Nieuwe, exotiosche agrarische gewassen van WUR (uit LN2050) inbouwen in RS en toevoegen aan de allocatie

### ISSUE THREAD

**Issue by BartRijken** [ObjectVision/RSopen#124]
De allocatie van deze gewassen gebeurt qua geschiktheidskaarten niet obv NPV maar obv kansenkaarten (van 0-10 bijv). @jipclaassens Hoe laten we deze concurreren met de traditionele landbouwklassen die al in RS zitten? Samen in disc alloc opnemen?

**Comment by jipclaassens** [comment]
@BartRijken we zullen het moeten uitdrukken in eur_ha. Het moet immers een vergelijkbare orde grootte hebben. Dus kunnen we experts hier nog iets zinnigs over laten zeggen?

**Comment by BartRijken** [comment]
> @BartRijken we zullen het moeten uitdrukken in eur_ha. Het moet immers een vergelijkbare orde grootte hebben. Dus kunnen we experts hier nog iets zinnigs over laten zeggen?

Ja lijkt mij ook het beste. Ik ga checken bij experts of ze iets over euro's kunnen zeggen. Ik verwacht daar niet veel van (de kansen worden gebaseerd op regressie obv geobserveerd combinaties van bodems, grondwater en exotische gewassen).  

Alternatief 1: de kansen inlezen, en via disc alloc en schaduwprijzen omrekenen naar waarden die dicht tegen de euro's (NPV) liggen van de traditionele gewassen die mede gealloceerd worden. Dit zou toch moeten kunnen @jipclaassens, dat de alloc de euro's per ha teruggeeft die nodig zijn om de claims voor deze gewassen te realiseren?

Alternatief 2 (zie offerteverzoek): de exotische gewassen los alloceren van de traditionele gewassen, na de alloc van die trad gewassen. Een nieuwe sector en subsectoren dus, voor exotische gewas alloc. Deze worden bijv gealloceerd op plekken waarvoor de NPV van alle traditionele gewassen lager dan, zeg, 0 was.

**Comment by jipclaassens** [comment]
@BartRijken, de kansenkaarten voor YR worden ingelezen. Maar de gewas typen moeten worden gelinkt aan model types, of er moeten extra model types komen.
