### ISSUE TITLE
Kansenkaarten (geschiktheidskaarten) nieuwe, exoptische gewassen inlezen in RS (zie issue #124)

### ISSUE THREAD

**Issue by BartRijken** [ObjectVision/RSopen#125]
Zie issue #124

**Comment by jipclaassens** [comment]
Stuur jij deze?

**Comment by BartRijken** [comment]
> Stuur jij deze?

Wordt aan gewerkt. Zie mail.Contactpersoon is Louden Kremer, van WUR (louden.kremer@wur.nl).
