### ISSUE TITLE
RunAll.cmd:/MaakBasedata/Generate_Run4 

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/RSopen#146]
RunAll.cmd
WindowsSystem Error: FileMapHandle(K:/LD/wlo2024/BaseData/Vastgoed/Estimates_detached_20220419.fss/LockFile.fss).OpenForRead:

![image](https://github.com/user-attachments/assets/3e1ddaf3-1b77-499b-9f4a-4a5e397c5313)
PD1193 https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/WLO2024

batch: GeoDMS 15.7.3

In 15.7.1 stopt btach gelijk
14.14.0: melding over een bg_polygon

**Comment by jipclaassens** [comment]
![image](https://github.com/user-attachments/assets/9e008a78-e713-42df-8424-7990d4c935a6)

**Comment by basvanbemmel** [comment]
Maar bij mij werkt het dus niet. Welke exe gebruik je?
Ik vermoed dat je iets runt in de GUI wat niet in de batch zit

**Comment by jipclaassens** [comment]
Nee, ik ben nog aan het debuggen. Maar waarschijnlijk bijna opgelost

**Comment by basvanbemmel** [comment]
![image](https://github.com/user-attachments/assets/58d501ea-49f6-4e1c-a34e-b295a39c6437)

BaseData en VariantData runne maar Allocatie start niet op, ik krijg weer die wat vreemde "0", een oud probleem volgens mij

**Comment by basvanbemmel** [comment]
ook na jouw bug-fix in versie 11205 nog steeds een 0 en klikken in het cmd window om verder te kunnen

**Comment by jipclaassens** [comment]
maar het werkt verder wel?

**Comment by basvanbemmel** [comment]
ik heb nog een probleem gedetecteerd, niet helemaal duidelijk wat het probleem is. Ik meld het vandaag nog

**Comment by basvanbemmel** [comment]
Het gaat om deze melding, mij onduidelijk of het nog een probleem is in BAU (WLO_Hoog) of het volgende scenario wat aan staat WBSA


![image](https://github.com/user-attachments/assets/096d576f-31d7-4804-9020-c55c2345f541)
![image](https://github.com/user-attachments/assets/126af72f-448c-4ccb-aa1a-b3ce87b396b2)

[progress]@@@@@ Logging ended for K:/PD/WLO2024/cfg/log/log_20241009_113220.txt at 2024-10-09 11:32:29
[memory]Highest Reserved in Blocks 9[MB]; Highest allocated: 0[MB]; Highest freed: 1[MB]; Highest uncommitted: 6[MB]; Highest CommitCharge: 73[MB]
Completed main.dms /Analysis/Allocatie/Zichtjaren/Y2030/Impl/Generate ?
ERROR: updating of item /Analysis/Allocatie/Zichtjaren/Y2030/Impl/Generate in main.dms failed.
batch will be aborted after pause because of a detected failure
Press any key to continue . . .

**Comment by basvanbemmel** [comment]
vermoed dat iets met dit te maken heeft

![image](https://github.com/user-attachments/assets/6b601ad3-d2e7-4992-b7a9-b5ac0d10d5fd)

**Comment by basvanbemmel** [comment]
Parkeer nog maar even ik heb al een vermoeden

**Comment by jipclaassens** [comment]
Ik begrijp hieruit dat er een scenario bestaat dat WBSA heet en dat je dat hebt gemaakt? Run je dat ook in de batch? Heb je dat aanstaan? heb je de variant data daarvoor gemaakt?

**Comment by basvanbemmel** [comment]
Dat is precies het probleem stond niet aan in de batch
het runt op dit moment

**Comment by basvanbemmel** [comment]
WSBA loopt op TeNat vast, is iets met casting van de domeinen naar compactedAdminDomain  vermoed ik

Domain mismatch between the specified Domain (/CompactedAdminDomain : UInt64) and the domain of the results of the calculation ( {-25, 25}*EPSG:28992�ngr_layer+{625000, 0}: IPoint) (different ValueTypes)
/Analysis/Zeef_AdminDomain/Wonen/eengezins_VrijeSector/Src/TeNat 

		attribute<bool> TeNat                                   (CompactedAdminDomain) := = WonenOfWerken && NietBouwenWaarNat ? 'SourceData/Water/TeNat/'+Klimaatscenario_ref+'/IsNat[AdminDomain/AllocDomain_rel]' : 'const(false, CompactedAdminDomain)';

**Comment by basvanbemmel** [comment]
Ik heb wel gecast, maar kom nu niet echt verder
Hele vage melding

![image](https://github.com/user-attachments/assets/b3ff7499-c144-4105-8d2a-d91f3d6523a6)

**Comment by basvanbemmel** [comment]
De aanmaak van de variantdata WBSA gaat niet goed, domeinprobleem op een TeNat bestand. Ik dacht dat ik het opgelost had maar toch niet. BAU gaat overigens wel helemaal goed (zowel variantdata en allocatie). 
Kun jij ernaar kijken (WBSA dus aan zetten in main.dms)

![image](https://github.com/user-attachments/assets/cc435196-6919-49f4-8ee9-3ecc3536edf4)

![image](https://github.com/user-attachments/assets/a6c22da3-3b15-4a93-af8d-1b8a94ec8a15)

**Comment by basvanbemmel** [comment]
En op Allocatie Verdichting krijg ik

![image](https://github.com/user-attachments/assets/615bdba9-175a-4bd9-a727-f91d37da1a85)

**Comment by jipclaassens** [comment]
Yes, te nat gefixt. ik loop nu het hele proces door

**Comment by jipclaassens** [comment]
hij lijkt het bij mij nu te doen.

**Comment by basvanbemmel** [comment]
Ok mooi

**Comment by basvanbemmel** [comment]
2 vragen:
- hij lijkt het te doen heeft dat ook nog betrekking op mijn opmerking over IsOntwikkeldePartij? Ik vermoed van niet
- Moet ik basedata ook weer runnen? Ik vermoed van wel als ik de codewijziging zie

**Comment by jipclaassens** [comment]
Nee en nee.

**Comment by basvanbemmel** [comment]
Waarom close je dit issue nu eigenlijk? Er is nog een probleem met "IsOntwikkeldePartij" bij Verdichting.

**Comment by jipclaassens** [comment]
haha, dit lijkt een vraag te zijn aan mij. En volgens mij is dit opgelost. Vandaar dat ik m sluit. Is t nu wel of niet nog een issue?

> hij lijkt het te doen heeft dat ook nog betrekking op mijn opmerking over IsOntwikkeldePartij? Ik vermoed van niet

**Comment by basvanbemmel** [comment]
Het is nog een issue (net zoals het 0-probleem ook nog steeds een issue is)

net weer gedraaid maar loopt dus vast op:
 Unknown identifier 'Src/IsOntwikkelendePartij'

Het gaat om de Treden voor het "Uitleg" scenario
![image](https://github.com/user-attachments/assets/56011713-97c4-405b-8502-67f955acdc21)

Dus voor de volledigheid

BaseData draait goed
VariantData voor alleen Uitleg niet

**Comment by basvanbemmel** [comment]
Ook nog een probleem met Allocatie WBSB. Daar kan 2050 niet worden uitgerekend door ontbreken van alle 2040 resultaten.
Gekke is dat WBSB identiek is aan WBSA aangaande instelling (gewoon code-technisch gekopieerd)

![image](https://github.com/user-attachments/assets/337d29a3-9f51-4b5c-8b18-b00d81d8cc0b)


Allocatie van BAU en WLO_Hoog_WBSA is wel goed gegaan (alle zichtjaren)

**Comment by basvanbemmel** [comment]
Allocatie WBSB 2040 is nu wel goed gegaan bij nogmaals aanzetten. Hopelijk niet een of andere willekeurig iets of er iets weggeschreven wordt (ik heb genoeg schijfruimte en 192GB intern)

**Comment by jipclaassens** [comment]
Ik zal het straks nog even fixen wat er mis is. Toegegeven, ik ben de 2040 tussenstappen vergeten te checken.

**Comment by basvanbemmel** [comment]
prima

**Comment by basvanbemmel** [comment]
Ik had vannacht de batch (RunAll.cmd) aangezet maar moest toch weer op een knop drukken om de batch verder te laten lopen.
Hoe kan dat? Dat was toch opgelost.
Te maken met rev 11236?

**Comment by basvanbemmel** [comment]
helaas wederom weer problemen

![image](https://github.com/user-attachments/assets/8b3b3b12-784c-43ac-af69-a069b1901795)

**Comment by basvanbemmel** [comment]
Ik moest claims met de hand runnen in de GUI om verder te kunnen. Enig idee hoe dat kan?
In dit stadium is het wel heel erg van belang dat die batch goed blijft werken met name als je gevoeligheidsanalyses wil gaan uitvoeren op parameters. Helaas zijn ook de technische doorlooptijden ook langer geworden.
Kun je WLO-Hoog en WLO-Hoog tegelijkertijd aanzetten in de batch of is dat niet de bedoeling?

**Comment by jipclaassens** [comment]
Waarschijnlijk gefixt. Claims werden vanuit batch gegenereerd met de GUI instelling van het WLO scenario. In de batch wordt hoog of laag pas bij de allocatie ingesteld...

Alleen de claims in de variant data zijn scenario afhankelijk. Ik heb het er nu even ingehackt. Voor volgende projectne doen we dit beter/is het niet nodig.

Daarnaast heb ik de error handling in het script aangepast, dus geen pauze meer.
