### ISSUE TITLE
Claim realisatie wonen/werken controleren

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#148]

**Comment by jipclaassens** [comment]
![Image](https://github.com/user-attachments/assets/e40a713b-f36e-4d80-9aa9-5705feca2c21)

**Comment by jipclaassens** [comment]
Fixed

![Image](https://github.com/user-attachments/assets/547fdc6c-e887-42f8-b45b-e9daed9d2b2e)

**Comment by jipclaassens** [comment]
check NL

**Comment by jipclaassens** [comment]
Verblijfsrecreatie is maar 0.64, waarom?

![Image](https://github.com/user-attachments/assets/d007cd68-438b-4954-8547-704f4cc8246b)

Logistiek is 0, waarom?

![Image](https://github.com/user-attachments/assets/fd269c15-b77d-488d-b149-eccb4669c123)

Landbouw gaat goed:

![Image](https://github.com/user-attachments/assets/5df57ba6-fee9-48b7-86ce-b377e49dc301)

**Comment by jipclaassens** [comment]
Logistiek footprint berekening klopte niet, nu wel:

![image](https://github.com/user-attachments/assets/6a427d50-5cea-455e-8841-dc1dc752f0d7)

**Comment by jipclaassens** [comment]
To do; check NL

**Comment by jipclaassens** [comment]
![Image](https://github.com/user-attachments/assets/efe5e352-d9f1-463a-acc3-4e9525c23641)

overheid gaat nog niet goed. Verder alles oke

**Comment by jipclaassens** [comment]
Fixed:

![Image](https://github.com/user-attachments/assets/e01a4dfb-41ec-41ab-bc80-65f79cd9c5fd)

**Comment by jipclaassens** [comment]
@basvanbemmel @BartRijken 

De claim realisatie van een aantal werksectoren VOOR allocatie is al groter dan 100%....
Oftewel, de TIGRIS claims matchen niet met LISA.

![Image](https://github.com/user-attachments/assets/69058564-4d35-4788-a577-215b8ca614ad)

**Comment by BartRijken** [comment]
Ik ga hier niet over, maar goed om dit in de nieuwe wlo even netjes af te stemmen met tigris @basvanbemmel en @jipclaassens
