### ISSUE TITLE
Voeg plancapaciteit toe aan materialen branch

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#15]

**Comment by basvanbemmel** [comment]
Volg ik eigenlijk niet.
De MateriaalStromen in git (ik zie hem trouwens niet staan) is toch een afgeleide van:
RSLight2021_ontwikkel_3 (rev 9987) met GeoDMS  11.3.1. 4 juli 2023

Daarin zit toch al plancapciteit?
