### ISSUE TITLE
knoop doorhakken: huidige opbrengstenderving vervangen door die uit wwl?

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#155]

**Comment by BartRijken** [comment]
@jipclaassens:

Ik zie dat er alleen iets wordt ingelezen voor gras:
/SourceData/Landbouw/WaterWijzerLandbouw 

Ik ben op zoek naar de opbrengstendervingskaarten (grids met fracties tussen 0 en 1)  voor _alle_ waterwijzerlandbouw klassen, incl bijbehorende unit (de WWL klassen). die had Chgarlotte gestuurd toch? Kan je ze inlezen voor each klasse?
