### ISSUE TITLE
evident benut nalopen, voor bau en wbs 

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#156]

**Comment by jipclaassens** [comment]
@BartRijken het IJ in Amsterdam wordt nu volgebouwd omdat hier plannen voor zijn en daarmee de andere reedsbenut wordt omzeild.

Dit lijkt me niet wenselijk:

![Image](https://github.com/user-attachments/assets/2ab4dc41-5ec2-4b06-8935-cd6815fc454b)

`/VariantData/Zeef/Y2050/SectorXSubsectoren/Wonen/meergezins_VrijeSector/Beschikbaar`

**Comment by BartRijken** [comment]
> [@BartRijken](https://github.com/BartRijken) het IJ in Amsterdam wordt nu volgebouwd omdat hier plannen voor zijn en daarmee de andere reedsbenut wordt omzeild.
> 
> Dit lijkt me niet wenselijk:
> 
> ![Image](https://github.com/user-attachments/assets/2ab4dc41-5ec2-4b06-8935-cd6815fc454b)
> 

Gefixt als het goed is (door o.a. overig binennwater op reeds benut te zetten voor alle sectoren).

**Comment by jipclaassens** [comment]
Na jouw laatste commit:
![Image](https://github.com/user-attachments/assets/daf7feb7-0933-4d56-9547-0f912d7a0a01)
