### ISSUE TITLE
Allocatie runnen voor NL voor BAU en WBS met 100% claimrealisatie

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#158]
- [ ] 'bij'-kaartje maken wonen/werken
- [ ] bijbehorende schade berekenen met ssm
- [ ] de kaartjes en grafieken in een presentatie zetten

**Comment by jipclaassens** [comment]
Blocked by EvidentBenut issue #156 @BartRijken

**Comment by jipclaassens** [comment]
WLO_Hoog_WBS:
subsector_rel

Lijkt me vrij veel, maar oke, er is veel groei verwacht.
![Image](https://github.com/user-attachments/assets/91479c28-35c5-482a-b9f8-930f333714b8)

Maar zuid-limburg?!
![Image](https://github.com/user-attachments/assets/860a41bf-ef62-4462-94eb-51c2ee41c8af)

Claim = 325k
Huidig = 150k

**Comment by jipclaassens** [comment]
Possible culprit:

`/sourcedata/Vastgoed/BAG/PerJaar/Y2022/pand/Uitsmeer_key/Read_AdminDomain_in_all_panden/AdminDomain_rel`
![Image](https://github.com/user-attachments/assets/b97295b5-72a1-421c-8466-3b805663ded4)

**Comment by jipclaassens** [comment]
Maarten heeft een poly2allgrid operator gemaakt die de rekentijd waarschijnlijk van 7 uur per BAG jaar naar minder dan een minuut terug brengt. Ik ga die even inbouwen.

**Comment by jipclaassens** [comment]
Gevonden:
lower_bound/upper_bound in rdc_meter_studyarea waren omgedraaid.

**Comment by jipclaassens** [comment]
> Gevonden: lower_bound/upper_bound in rdc_meter_studyarea waren omgedraaid.

nee, dit lost het nog niet op.

**Comment by jipclaassens** [comment]
Nu wel gefixt:
xy/min/max stonden hardcoded, terwijl extend rdc_meter obv shapefile waren gedefinieerd. Dit liep spaak bij de id opzoek actie via modulo.

**Comment by jipclaassens** [comment]
![Image](https://github.com/user-attachments/assets/ca7b61cb-5a7a-4b89-b5f6-807d2605af6a)

**Comment by jipclaassens** [comment]
@BartRijken @basvanbemmel  ik zie oa veel allocatie in Zuid Friesland. Realistisch?

stand 2022 volgens BAG: 13k EG VS
stand 2050: 40k EGVS
claim 2050: 40k EGVS

Waarom is de claim zo hoog? 

![Image](https://github.com/user-attachments/assets/c7fa7102-b64f-406f-913e-1a0a66180fef)

**Comment by jipclaassens** [comment]
Voor werken overshoots, zie https://github.com/ObjectVision/RSopen/issues/148#issuecomment-2426408066

**Comment by jipclaassens** [comment]
> > [@BartRijken](https://github.com/BartRijken) [@basvanbemmel](https://github.com/basvanbemmel) ik zie oa veel allocatie in Zuid Friesland. Realistisch?
> > stand 2022 volgens BAG: 13k EG VS stand 2050: 40k EGVS claim 2050: 40k EGVS
> > Waarom is de claim zo hoog?
> 
> De regionale claims per subsector zijn voor dit project een gegeven. Wil ik niet ter discussie stellen, tenzij er technisch iets fout gaat bij/na het inlezen van de claims uit Tigris. [@jipclaassens](https://github.com/jipclaassens) kan je checken of dit het geval is, door even naar de tabel te kijken uit Tigris die we inlezen?
> 
> Sowieso is de pl;ausibiliteit van west friesland voor mij lastig te checken in dit kaartje. als je een kaartje maakt van heel Frielsland of, beter nog, heel NL kan ik dit gebiedje vergelijken met andere regio's.

Geeft dit meer info? 
![Image](https://github.com/user-attachments/assets/4a1f61d1-264e-4747-be0f-82c9a34d209a)

Daarnaast:
TIGRIS claims voor eengezins FR = 265k
Startstate = 250k
Realisatie = 295k

Ik ga deze overshoot onderzoeken.

**Comment by BartRijken** [comment]
> De claim csv in de SD waren mysterieus onjuist...
> 
> Rerunnen vanuit de privdata veranderde dit, en nu lijkt het een stuk plausibeler.
> 
> ![Image](https://private-user-images.githubusercontent.com/48675272/378456420-6a8eed42-998c-4428-8d4c-b3da19287029.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MjU5MTYsIm5iZiI6MTcyOTUyNTYxNiwicGF0aCI6Ii80ODY3NTI3Mi8zNzg0NTY0MjAtNmE4ZWVkNDItOTk4Yy00NDI4LThkNGMtYjNkYTE5Mjg3MDI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE1NDY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNzM0NDU1NjE1MjliMzAzYTc1MTM1MzJmZGVjY2EyYzliNDYwMjY0ZDhiYTc4MmZkNzhiYzg2MmRhMDk0NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0iygSQsK_P9GK3Ncf1_P-5-xLZaupBOVP-RiYxWdmRg)

Mooi dat het opgelost is. 

Graag ff de claimrealisatie erbij zetten in de presentatie.

Check ook ff de claimrealistie op NL schaalniveau. Die mag je ook in de presentatie  zetten.

Hoe kon de csv 'mysterieus'  erkeerd zijn aangemaakt? Dat baart me wel beetje zorgen.

**Comment by jipclaassens** [comment]
Done: [20241024 - RVF NL resultaten.pptx](https://github.com/user-attachments/files/17505917/20241024.-.RVF.NL.resultaten.pptx)
