### ISSUE TITLE
Maak metPlancapaciteit branch aan, en voeg hier plancapaciteiten aan toe

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#16]

**Comment by basvanbemmel** [comment]
Dit is in het kader van de WLO toch? 
Moeten we daar Trello niet voor gebruiken. Zo niet dan zou ik zeggen als titel:

WLO: Maak metPlancapaciteit branch aan, en voeg hier plancapaciteiten aan toe

Maar eigenlijk is het dan per defintie geen RSOpen meer

**Comment by jipclaassens** [comment]
Klopt, voor WLO maar ook voor de materiaalstromen. Dus ik heb nu een branch van RSopen gemaakt die heet 'metPlancapaciteit' deze edits kan ik dan makkelijk in materiaalstromen mergen. Maar ook naar WLO als we daar een branch voor hebben. 

Het is dan niet helemaal open meer. Maar, de main branch blijft gewoon open met daarbij enkele varianten (branches) die wel extra data behoeven.

**Comment by basvanbemmel** [comment]
Ok maar voor Materiaalstromen was het toch essentieel dat er met de versie wordt gewerkt die al uitgeleverd was naar TNO.
Hoewel je de materiaalstromen-scripts hebt overgeheveld is de " overige code"  toch niet gelijk aan die in RSLight2021_ontwikkel_3. Ik vrees dat het resultaat niet gelijk is ( zie ok issue: https://github.com/ObjectVision/RSopen/issues/7 kijk ik vandaag nog naar)
