### ISSUE TITLE
WLO2024: WLO-Laag werkt niet

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/RSopen#160]
Als ik de batch voor WLO-Laag aanzet krijg ik na verloop van deze tijd deze melding (zie screendump).
Lijkt of WLO-Hoog wordt berekend onder Variantdata Claims, Ik zie zie namelijk wel aangemaakt worden:
K:\LD\WLO2024\VariantData\Claims\WLO_hoog_BAU\Y2030\NVM\Wonen.fss

![image](https://github.com/user-attachments/assets/37db482f-a486-4cf0-a6f6-c39d0ff4eab3)

**Comment by jipclaassens** [comment]
verblijfsrec claims werden niet ontkoppeld, geen idee waarom dat niet ozu gebeuren. Maar het is ook eignelijk niet nodig, dus die param op false gezet. En dan werkt het.
