### ISSUE TITLE
Extra klasses reedsbenut uit BGT definieren

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/RSopen#172]
Uit modelleerresultaat blijkt dat veel ontwikkelingen (groene cellen) op lokale wegen uit de BGT liggen, zeer onwaarschijnlijk ons inziens

![image](https://github.com/user-attachments/assets/89a354bf-3317-4f95-b1bf-3c5c59c6d8f2)

**Comment by jipclaassens** [comment]
Wat heb je precies uitgerekend? Want al die plekken zijn gewoon ReedsBenut bij mij en allocatie resultaat zit het ook niet in:

![image](https://github.com/user-attachments/assets/83090231-5b4f-4a02-a7ec-c0c915c0f5b3)

**Comment by basvanbemmel** [comment]
Groen was wonen (subsector_rel 2060) voor HOOG-BAU in versie V11223 inmiddels is dat gewijzigd door wijzigingen in BBG Reedsbenut. Blijft onverlet dat voor BGT Reedsbenut ook goed moet worden gezet (en dat het overlap heeft met BBG Reedsbenut doet doet eigenlijk niet terzaken). De vraag is dus eigenlijkk kun jij de BGT-klassen doorlopen en definieren welke volgens jouw op ReedsBneut dienen te staan. Dan hebben we een goed startpunt en kunnen wij het bekijken.

**Comment by basvanbemmel** [comment]
En op (de meeste) lokale wegen zie je nu inderdaad ook geen allocatie meer?

**Comment by jipclaassens** [comment]
![Image](https://github.com/user-attachments/assets/2a62272f-dea0-4934-a6f4-130328e3f0c0)

Ja, maar ik heb die lokale wegen niet geexcludeerd. Dat lijkt me erg restrictief. Dan kun je nog moeilijker herontwikkelen. Je ziet toevallig een gat in De Meern. Want bouwjaar && gevaar niet restrictief tov wijk ernaast.
