### ISSUE TITLE
WLO2024: trage Allocatie in 15.10.2 OperPot

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/RSopen#173]
zoals besproken op 4 november:
![image](https://github.com/user-attachments/assets/980057d9-5dd9-4358-b91f-28643136562e)

**Comment by basvanbemmel** [comment]
runnen met 256 GB lijkt niet heel veel sneller tov 192GB.

die OperPot is o.a. relevant bij:
Read from K:/LD/WLO2024/VariantData/Claims/WLO_Hoog_Uitleg/Y2040/NL/Wind.fss [[/Analysis/Claims/Y2040/AllocRegios/NL/Result/read/Wind/Totaal]]

**Comment by basvanbemmel** [comment]
Is hier al iets over te melden eigenlijk?
2060 lijkt ook trager dan 2030,2040 en 2050, wellicht dat eindjaar anders werkt?

**Comment by basvanbemmel** [comment]
Ik heb het vermoeden dat de traagheid te maken heeft dat de zichtjaren dubbel worden uitgerekend.
Dus 2030 wordt berekend, 2040 rekent ook weer 2030 uit (en schrijft bestanden weg), 2050 rekent ook weer 2030 en 2040 uit en 2060 doet het langst die moet 2030,2040 en 2050 uitrekenen. Ik vermoed dit omdat er ook tmp-files worden weggeschreven.
Ik kan mij niet herinneren dat dit gedrag ook bij de Planmonitor 2024 was.

![image](https://github.com/user-attachments/assets/f52d7d02-a23a-4e9c-b74b-72956a08e706)

**Comment by jipclaassens** [comment]
Ik zie t al, deze moeten op TRUE staan...

![image](https://github.com/user-attachments/assets/c8f21f19-dd88-4da1-b91f-3618c0ef131d)

**Comment by jipclaassens** [comment]
nee, die stand2030Ontkoppeld en volgende op true

**Comment by basvanbemmel** [comment]
ok

**Comment by jipclaassens** [comment]
Opgelost? @basvanbemmel

**Comment by basvanbemmel** [comment]
Ja het is nu sneller
