### ISSUE TITLE
DS/WLO24: Conversie TIGRIS-output landuse.dat labour.dat naar csv-bestand

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#18]
De conversie (dat naar csv) vond plaats in:
/PrivData/TigrisXL/Cases/WLO_hoog/GR/Tables/Labour/Zichtjaren/Y2030/Attributes
PD 1048 en verder: https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/RSLight2021_ontwikkel_3

Let op is niet meer aanwezig in RSOpen!

Opnieuw draaien voor:
- Hoog en Laag
- 3 graden scenario en 2 graden scenario ("Parijs")
Aldus voor nu 4 csv bestanden

**Comment by jipclaassens** [comment]
Toevoegen hier:

/CaseParameters/Claims/WonenEnWerken/Cases/WLO_laag/SW/Tables/Labour/Zichtjaren/Y2030/

Dan hier container om .dat in te lezen
en dan ook hier de aggregatie naar NVM
.dat files blijven priv en dus niet in de SD.

**Comment by jipclaassens** [comment]
Nog inbouwen in RSopen

**Comment by basvanbemmel** [comment]
Dit kan toch niet op closed?
Moet toch ook worden aangeroepen in:
https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/RSLight2021_ontwikkel_3_PlanMonitor2023

Daarnaast staat het nu in de SD van RSOpen en in RSXL?

**Comment by basvanbemmel** [comment]
Ok en dan is het bedoeling om de aangemaakte bestanden over te hevelen naar de SD van RSXL?
RSLight2021_ontwikkel_3_PlanMonitor2023 werkt namelijk met de SD van RSXL
