### ISSUE TITLE
Ruimtelijkk clusteren van de 40% van de kansenkaarten verziliting

### ISSUE THREAD

**Issue by BartRijken** [ObjectVision/RSopen#182]
Pending for in out from Janneke Pouwels. Gebruik voorlopig een potentiaalfunctie.

**Comment by BartRijken** [comment]
@jipclaassens  waarom blocked? _Gebruik voorlopig een potentiaalfunctie._

**Comment by jipclaassens** [comment]
ik had de 'voorlopig' gemist

**Comment by jipclaassens** [comment]
![Image](https://github.com/user-attachments/assets/0730284f-7996-4095-8c22-9aa8f6768ff9)
