### ISSUE TITLE
Port WLO varianten/updaten naar RSOpen_WLO

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#193]
- [x] Claims
- [x] VariantK
- [x] ReedsBenut
- [x] Zichtjaar 2060
- [x] BBG2020

**Comment by basvanbemmel** [comment]
De lijst is zeker langer, we reageren morgen zo snel mogelijk

**Comment by basvanbemmel** [comment]
krijgen nu deze error (ontbrekend bestand blauwe stad)

![image](https://github.com/user-attachments/assets/fb48ef7c-d2c6-43a9-92a0-13a393f52f30)

**Comment by basvanbemmel** [comment]
Ja, kan zijn dat we bepaalde elementen nog heropenen maar dan zal ik specieker zijn (nieuw issue)
