### ISSUE TITLE
N2000 dat uit zee bestaat uit de NabijN2000_Premie halen

### ISSUE THREAD

**Issue by BartRijken** [ObjectVision/RSopen#198]
Zie item: /VariantData/Suitability/Y2050/Landbouw/per_ModelType/Rietteelt/NabijN2000_Premie

In RVNL gebruikten we een N2000 kaart (ghemaakt door WUR) zonder zee. In groenland. Voor buffers. Misschien kan je die vionden/gebruiken

**Comment by jipclaassens** [comment]
![Image](https://github.com/user-attachments/assets/17cd667a-8609-44fe-95bb-0ed296cedc78)

en zo? als de kustlijn wel erin zit?

**Comment by jipclaassens** [comment]
![Image](https://github.com/user-attachments/assets/7557c8d2-b218-4179-8671-bd6526a307f2)
 zonder waddenzee/noordzeekustzone/ijsselmeer
