### ISSUE TITLE
Materiaalstromen simpel/complex opzetje maken

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#2]
**1. Optoppen van appartementen**
  - Simpel: per gemeente aantal woningen, trek van je claims af. Verdeling over NL obv ratio van aantal appartementen in gemeente. 
    - Output: niet robuust op gridniveau qua allocatie, maar wel op gemeenteniveau, want de opgetopte woningen zijn niet exact op de kaart te zetten. We verdelen de opgetopte woningen random over de cellen met appartementen. Eventueel met hoogte restricties die de kans op optopping beinvloeden.
    - Tijd: 1 dag
  - Complex: die claims van simpel alloceren met geschiktheid waarin je platte daken, lage gebouwen meeneemt. Platte daken identificeren en toevoegen kost wel veel tijd. Allerlei parameters nodig: minimaal oppervlakte, minimale hoeveelheid toe te voegen appartementen. Dit heeft nog veel denkwerk nodig om het concreet te maken. En hoe om te gaan met niet woningen optoppen? Ook een optie?
    - Output: wel gewoon grids.
    - Tijd: veel, 3 dagen.
  
**2, Splitsen van woningen in kleinere woningen**
  - Simpel: per gemeente aantal woningen, trek van je claims af. Verdeling over NL obv ratio van aantal appartementen in gemeente. 
    - Output: niet robuust op gridniveau qua allocatie, maar wel op gemeenteniveau, want de gesplitste woningen zijn niet op de kaart te zetten. We verdelen de gesplitste woningen random over de cellen met woningen die we daarvoor geschikt achten. Grote app, vrijstaand?
    - Tijd: 1 dag
  - Complex: kijken naar woningen met drempel waarde voor m2. Iets bedenken voor geschiktheid. Waarom de ene wel en andere niet? Welk type woning wil je splitsen? Bouwjaar/type klassen? 
    - Output: wel gewoon grids.
    - Tijd: 2 dagen.

**3. Kleiner bouwen, nieuwbouw kleiner m2 geven per woningtype**
   - Simpel: Ontwikkelpakket instellingen aanpassen, kan eventueel ook in Hestia. 
    - Output: grids
    - Tijd: weining, kan met huidige instellingmogelijkheden, 4u

**4. Bouwtypes anders, verschuiving van te bouwen woningtypes**
  - Simpel: claims van een/meergezins bouw aanpassen. Verdeling over NL obv ratio van aantal een/meergezin in gemeente 
    - Output: grids
    - Tijd: weinig, 4u

**5. Transformatie van niet-wonen naar appartementen**
  - Simpel: post-processing, sloop-nieuwbouw van niet-wonen naar wonen identificeren. En oormerken als transformatie. Wellicht wordt de taakstelling al behaald, wanneer dit niet het geval is accepteren we een onderrealisatie.
    - Output: grids
    - Tijd: weinig, 4u
  - Complex: Geschiktheid voor kantoor (en evt andere functies) verhogen via kosten/opbrengsten. Iteratief proces voor de bepaling van de verandering van die geschiktheid. Trial en error.
    - Output: grids
    - Tijd: veel, 2 dagen.

**6. Levenduurverlenging, renovatie om sloop te voorkomen. (Moeten we hier wel iets mee doen? aantallen zijn zeer klein)**
  - Simpel: post-processing in Hestia?  
  - Complex: In RS: instelling woningen gebouwd na jaar X worden niet gesloopt. Welk type woningen zou je hierovor willen aanmerken? Jaren '80 woningen? Of bepaald energielabel? Optie: sloopkosten kunnen verhogen. Maar ook hier iteratief proces nodig om de verandering te bepalen. Trial en error.
    - Output: grids
    - Tijd: veel, 2 dagen.

**Comment by basvanbemmel** [comment]
maar even op open gezet, anders moet je filter op closed zetten of url met issuenr 2 precies weten. Is niet handig. Sowieso niet echt een issue maar een werkinstructie.

**Comment by jipclaassens** [comment]
1. **Optoppen**: Geen actie in RS, want we veronderstellen dat X aantal woningen die door sloopnieuwbouw zijn neergezet, eigenlijk door optopping zijn gerealiseerd
2. **Splitsen**: In RS: We passen de claims aan zodat er minder ruimtevraag naar woningen komt. 
3. **Kleiner bouwen**: In Hestia
4. **Andere typen**: dit zit wellicht al in de 4 RV varianten. @basvanbemmel controleert dit en maakt een tabelletje
5. **Transformatie**: RS-post, identificeer waar wonen kwam ipv niet-wonen. En classificeer dat als transformatie
6. **Levensduur**: in Hestia
