### ISSUE TITLE
Verschil in agrarisch landuse tussen alloc resultaat en landgebruikskaart

### ISSUE THREAD

**Issue by BartRijken** [ObjectVision/RSopen#206]
Landgebruikskaart: /Indicatoren/Y2050/Landgebruikskaart/Result_SA
Alloc resultaat: /Indicatoren/Y2050/Stand/Subsector_rel

Zie bijv de klasse: rijst.

**Comment by jipclaassens** [comment]
Subsector_rel ==  rijst
![image](https://github.com/user-attachments/assets/49f8cb6a-cb06-400e-a88d-91088018d6fe)

lu == overig
![image](https://github.com/user-attachments/assets/4c867c75-6388-4f83-9e8c-197c577c224b)


Want: 
![image](https://github.com/user-attachments/assets/6c9cb0e9-67fb-4783-9702-b52efe3eb44d)

**Comment by jipclaassens** [comment]
![image](https://github.com/user-attachments/assets/d70a6b99-6870-4f5a-a5a9-65442b26ecc2)
 meer dan de helft van de 100m cell is beschikbaar uit de 25m cellen. Dus is alloceerbaar. Maar later blijkt de cell al overig (lees: niet agrarisch) en dus wordt niet overschreven. Is dit nog wenselijk?

**Comment by jipclaassens** [comment]
@BartRijken hier moeten we even over overleggen wat we hiermee willen doen.

**Comment by jipclaassens** [comment]
oplossing -> #215

**Comment by jipclaassens** [comment]
Dit probleem tussen admin/alloc domain in beschikbaar is nu opgelos door te alloceren op 25m. Maar nog steeds zie ik alleen rijst op gg overig_totaal terecht komen, waarom?

**Comment by jipclaassens** [comment]
![Image](https://github.com/user-attachments/assets/828e8a96-b385-46c1-bb2b-2a61deb5bec3)

**Comment by jipclaassens** [comment]
Allocatie van rijst:
![image](https://github.com/user-attachments/assets/3696e343-708d-4991-9497-38de23515683)

Precies daar waar de prev gg_LandbouwK undefined is, en daardoor de transitiekosten 0 worden, door een makedefined(x,0) `/VariantData/Suitability/Y2050/Landbouw/per_ModelType/rijst/Conversion_costs`

**Comment by jipclaassens** [comment]
Oftewel, @BartRijken welke transitie kosten hangen we aan deze overgangen. Willen we uberhaupt dat er landbouw komt op niet-landbouw cellen? 0 is iig niet goed.

**Comment by jipclaassens** [comment]
Ik zie in WBS altijd een onderrealisatie, dit komt door het exogeen opleggen. We halen zoveel cellen uit de mogelijke locaties (door null waardes in de suitability hiervoor op te geven) dat er onvoldoende ruimte is.

**Comment by jipclaassens** [comment]
> Ik zie in WBS altijd een onderrealisatie, dit komt door het exogeen opleggen. We halen zoveel cellen uit de mogelijke locaties (door null waardes in de suitability hiervoor op te geven) dat er onvoldoende ruimte is.

Bij `/ModelParameters/Landbouw/claims_ggvee_minfractie` niet refereren naar `StartYear/Akkerbouw` verwijzen naar StartYear minus ExogeenOpleggen dan worden dus de min-claims automatisch lager.

**Comment by jipclaassens** [comment]
@BartRijken, ter info: ik had gewoon jouw laatste edits niet binnengehaald.

En twee: de MinimalLandAvailability_Landbouw werkt goed om geen enkele 25m celletjes landbouw ergens te alloceren. Maar je hebt nu wel enkele subsector celletjes, is dat wenselijk?

![image](https://github.com/user-attachments/assets/60ec695b-f656-4657-abf2-cc450f1797cc)

**Comment by jipclaassens** [comment]
> En twee: de MinimalLandAvailability_Landbouw werkt goed om geen enkele 25m celletjes landbouw ergens te alloceren. Maar je hebt nu wel enkele subsector celletjes, is dat wenselijk?

Bart vindt dit prima.

**Comment by jipclaassens** [comment]
Helaas een nieuw issue. Ik heb de beschikbaarheid voor landbouw nauwer gemaakt.  Als er panden in het 25m celletje staan is het niet beschikbaar. Hierdoor worden de min-claims weer niet gehaald. 

tbc

**Comment by BartRijken** [comment]
> Helaas een nieuw issue. Ik heb de beschikbaarheid voor landbouw nauwer gemaakt. Als er panden in het 25m celletje staan is het niet beschikbaar. Hierdoor worden de min-claims weer niet gehaald.
> 
> tbc

Cellen van 25x25 meter met panden zouden niet beschikbaar moeten zijn voor landbouw. Even uiztoeken dus hoe het kan dat ze wel beschikbaar zijn. Dan alsnog onbeschikbaar maken, op een nette/robuuste manier. Vervolgens bij /ModelParameters/Landbouw/claims_ggvee_minfractie niet refereren naar StartYear/Akkerbouw verwijzen naar StartYear minus ExogeenOpleggen _minus 'niet beschikbaar'_. Dan worden de min-claims automatisch weer lager. Wat vind je van deze oplossingsrichting @jipclaassens ?

**Comment by jipclaassens** [comment]
3 cellen zijn landbouw in alloc en niet in lu kaart. Ik heb geen tijd om die laatste 3 op te sporen. Zullen wel wat vage grensgevallen zijn.

![Image](https://github.com/user-attachments/assets/4a79d7e4-f282-4002-a800-3877c37b475d)
