### ISSUE TITLE
WLO:  bebouwing Subsector_rel in klaverbladen snelwegen Ouderijn

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/RSopen#207]
f598630ffe44637275714036e1273dc6bf70a96a
https://github.com/pbl-nl/model-RSopen/tree/WLO

![image](https://github.com/user-attachments/assets/4e33a787-0b0c-4fa9-82de-8229e0cb8092)

**Comment by jipclaassens** [comment]
Fixed:

![Image](https://github.com/user-attachments/assets/e22c35a5-8b6d-49eb-807d-8d1c4fd44fbe)

Door snelwegen te inflaten/deflaten en in restrictief op te nemen.
