### ISSUE TITLE
Wat is de status van UNCHECKED items?

### ISSUE THREAD

**Issue by BartRijken** [ObjectVision/RSopen#212]

**Comment by BartRijken** [comment]
Zie bijv: /BaseData/StartState/StateBasisjaar/read/Landbouw/Rietteelt

**Comment by jipclaassens** [comment]
Wat bedoel je met status? Het doel? Er is eerder een issue geweest dat nog wel eens ongemerkt een tif werd weggeschreven die helemaal null was. Dus om ervoor te zorgen dat wat je inleest sowieso goed is (of iig niet allemaal zero of null) zit deze check stap ertussen.

**Comment by jipclaassens** [comment]
Descr toeveogen waar nodig.
