### ISSUE TITLE
WLO: activeren MinimumDichtheid_EG_WLO_hoog

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/RSopen#214]
Ik zie in VariantK.dms regels 33-36 (WLO PBL 3da07fb1790d68dd5a92061881bec60dfc4cea34)

MinimumDichtheid_EG_WLO_hoog
MinimumDichtheid_MG_WLO_hoog
MinimumDichtheid_EG_WLO_laag
MinimumDichtheid_MG_WLO_laag

uitbecommentarieerd.

Zou je deze weer aan kunnen zetten zodat ze ook echt aangeroepen worden?
Ik heb sterk het idee dat we ze nodig hebben.

**Comment by jipclaassens** [comment]
Done
