### ISSUE TITLE
DS: Ruimtescanner output genereren tbv Actualisatie Deltascenarios 2023

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#26]
Zoals telefonisch besproken:

We gaan de nieuwe TIGRIS claims, d.d. oktober 2023, gebruiken in de Ontwikkel3_PlanMonitor configuratie. Want de Deltascenarios maken enkel gebruik van al gepubliceerde resultaten. Voor de stedelijke ontwikkeling is dit Hoog/Laag voor BAU uit de PlanMonitor.

Dus ik heb nodig voor WLO hoog en laag, variant BAU, y2050, alle state variabelen.

**Comment by basvanbemmel** [comment]
Run15 (de eindrun) zou vandaag (maandag 16 oktober) geleverd worden door Marnix/Barry

**Comment by basvanbemmel** [comment]
Is dinsdag 17 oktober geworden
