### ISSUE TITLE
Hoe werkt het RuimteScanner - Tigris proces?

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#27]
**Het werkt als volgt (bron: Bart)**

1. RuimteScanner levert standgegevens van basisjaar (incl BAG nieuwbouw) en woningbouwmogelijkheden (zeef, dit bevat plancapaciteit).
a.	standgegevens in basisjaar (2021). Zie item: /NaarTXL/StandBasisjaar
b.	woningbouw na basisjaar dat volgens BAG al gebouwd is of in de pijplijn zit. Zie item: /NaarTXL/BAGNieuwbouw
c.	woningbouwmogelijkheden. Zie item: /NaarTXL/Woningbouwmogelijkheden
2. Vervolgens wordt deze output in Tigris gebruikt om basisjaar mee te synchroniseren en mee te 'fine tunen'. Ze doen een run rekening houdend met woningbouwmogelijkheden.
3. Evaluatie van Tigris output, PBL (Jan/Kersten)/Significance (Barry) controleren de resultaten, hoe verhoudt het zich tot andere studies/scenarios.
4. Vervolgens worden er nieuwe schotten/runs/iteraties uitgevoerd op basis van feedback uit de evaluatie. Tweaken in Tigris in de woningbouwmogelijkheden (_'gereguleerd draaien'_; dit in tegenstelling tot eerdere runs die vrije markt principes hanteren). 
5. Definitieve Tigris output wordt in de RuimteScanner gebruikt.

**Vervolgvraag**
- Met welke RuimteScanner variant en versie is stap 1 berekend i.r.t. de Tigris levering van oktober 2023?
  - Dit lijkt te komen uit Ontwikkel3 in augustus 2023.
- En welke is gebruikt voor de gepubliceerde plan monitor?

N.B.
- Tigris resultaten op LMS-subzone zijn priv. Aggregatie naar COROP is wel gepubliceerd.

**Comment by BartRijken** [comment]
Goede beschrijving

**Comment by basvanbemmel** [comment]
Helaas vat ik het nog steeds niet echt. Waarom worden de toekomst berekeningen uit TIGRIS in de Ruimntescanner dan niet gecheckt of het "past". Na allocatie kan het toch niet passen? Waarom alleen het basisjaar. Dinsdag werd in de WLO-vergadering dit namelijk gesuggereerd. Uit de notulen:


  •	We beginnen met de vier onzekerheidsverkenningen: 
  1.	Water en Bodem Sturend
  2.	Verdichting
  3.	Stedelijke Uitleg
  4.	Spreiding 
  Bas gaat na of hij alle informatie voor de RuimteScanner heeft om daarmee aan de slag te gaan. De werkwijze is: 
  1.	Met de RuimteScanner kijken naar de beschikbare ruimte 
  2.	Regionale verdeling met TXL
  3.	Vertaling naar ruimtegebruik met de RuimteScanner



Maar basisjaar is toch al gedaan dus er hoeft niets te gebeuren?

**Comment by basvanbemmel** [comment]
Nog steeds niet echt duidelijk, ook zou ik graag echt container-itembenamingen willen hebben waar het staat.

**Comment by jipclaassens** [comment]
> Nog steeds niet echt duidelijk, ook zou ik graag echt container-itembenamingen willen hebben waar het staat.

Uit mail Bart:
a.	standgegevens in basisjaar (2021). Zie item: /NaarTXL/StandBasisjaar
b.	woningbouw na basisjaar dat volgens BAG al gebouwd is of in de pijplijn zit. Zie item: /NaarTXL/BAGNieuwbouw
c.	woningbouwmogelijkheden. Zie item: /NaarTXL/Woningbouwmogelijkheden

**Comment by basvanbemmel** [comment]
Ik heb het er ook nog met Jan Ritsema over gehad. Enige wat mij nu nog niet duidelijk is is wat de rol is van de plancapaciteit. Je zou zeggen als die wijzigt dat je ook een soort nieuwe run tbv TIGRIS zou moeten doen. Ik neem dat wel met Barry Zondag op. Volgens mij doen we nu niets met de woningaantallen uit de plancapaciteit alleen de contour (dus ruimte)
