### ISSUE TITLE
Batch: check error level toevoegen

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#3]

**Comment by basvanbemmel** [comment]
Ik heb een hele run kunnen doen die wel helemaal doorliep.
Voor beide WLO's en 5 sceanrio's + aannmaak basedata en variantdata iets van 5 uur.

**Comment by basvanbemmel** [comment]
Ik krijg een soortgelijke error nu bij de totaalrun per 10 jaar voor alle sceanrios.
Zeef ontbreekt voor GL


![image](https://github.com/ObjectVision/RSopen/assets/24241780/a751c86d-b148-41d4-b576-c14309d2c3f1)

**Comment by basvanbemmel** [comment]
De laatste run is wel er helemaal doorheen gekomen (heb ik ook opgestuurd per filesender). Onvoorspelbaar gedrag aangaande de batch dus. Wel 2 keer in de zeef overigens. Wellicht dat IO zo snel is dat het wordt overgeslagen of zo.

**Comment by basvanbemmel** [comment]
Helaas tot niet goed gegaan. Ik zie nu dat StandY2050 niet is weggegeschreven voor WLO_Hoog_MO. Ik heb in de log gekeken maar zie niets vreemd. (geen error of zo)
