### ISSUE TITLE
MAT: runs/indicatoren 

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#41]
**Afspraak ovl 31 okt 2023:**
- Alleen WLO hoog
- 4 varianten uit RVNL + BAU
- Die 4 varianten uit RVNL zijn opzichzelf al de verhaallijnen die doorgerekend worden. Maar we doen er nog een schepje bovenop met de maatregelen
- Alle maatregelen worden simultaan toegepast
- We gebruiken RVNL branch
- Uitwisseling RS-Hestia, Hestia SD/RuimtelijkeOntwikkeling hier staat hoe Folckert het wil
- Uiterlijk 3 nov RS-output aan Folckert sturen

**Output:**
Basisjaar y2021 = 32 + 4 + 32 = 68 tifs
•	Aantal woningen per woningtype per energielabel = 4 * 8 = 32 tifs
•	Bouwjaar per woningtype = 4 tifs
•	Oppervlakte per woningtype per energielabel 4 * 8 = 32 tifs
 
Per decade, dus alles 3x = (4+4+4+4) * 3 = 48 tifs * 2 scenarios * 4 varianten * 6 maatregelen = 2304 tifs
•	Nieuwbouw aantallen per woningtype = 4 tifs
•	Nieuwbouw oppervlakte per woningtype = 4 tifs
•	Sloop aantallen per woningtype = 4 tifs
•	Sloop oppervlakte per woningtype = 4 tifs

product groep analyse woningbouw

**Comment by jipclaassens** [comment]
1. Optoppen: Geen actie in RS, want we veronderstellen dat X aantal woningen die door sloopnieuwbouw zijn neergezet, eigenlijk door optopping zijn gerealiseerd. Kijk of dit matched met overzicht Martijn
2. Splitsen: In RS: We passen de claims aan zodat er minder ruimtevraag naar woningen komt.
3. Kleiner bouwen: In Hestia
4. Andere typen: dit zit wellicht al in de 4 RV varianten. @basvanbemmel controleert dit en maakt een tabelletje
5. Transformatie: RS-post, identificeer waar wonen kwam ipv niet-wonen. En classificeer dat als transformatie. Kijk of dit matched met overzicht Martijn
6. Levensduur: in Hestia. Kijk of dit matched met overzicht Martijn

**Comment by basvanbemmel** [comment]
punt 4 (zoals in email van 1 november 2023)
[20231101_4_Bouwtypes_anders.xlsx](https://github.com/ObjectVision/RSopen/files/13235119/20231101_4_Bouwtypes_anders.xlsx)

**Comment by jipclaassens** [comment]
Aandelen zijn ook vrij constant

![image](https://github.com/ObjectVision/RSopen/assets/48675272/5a13a932-0d52-4b85-9613-6a269b1f3040)
