### ISSUE TITLE
Nieuwe TIGRIS claims regelen

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#47]
Nu is 2050 gekopieerd en 2060 genoemd als hack om het werkend te maken

**Comment by jipclaassens** [comment]
@basvanbemmel in de tigris run die je mij hebt gestuurd (run20), zitten geen varianten. Is dat de bedoeling? Alleen hoog en laag.

**Comment by basvanbemmel** [comment]
klopt ja is 3 graden scenario, alleen hoog en laag. Varianten komen nog

**Comment by jipclaassens** [comment]
@basvanbemmel hiervoor ben ik nog blocked vanwege de tigris ,dat kolom namen!

**Comment by basvanbemmel** [comment]
Hi Marnix en Bas,

Ik ben de Tigris output (run20) aan het inbouwen in de RuimteScanner voor de WLO.

Ik heb de zip met alle bestanden uitgepakt en zie hierin alleen wlo hoog en laag en geen varianten. Klopt dat?
Verder zitten er in de labour.dat 14 kollommen. Maar dit matched met geen enkele vorige levering en ik kom ook geen bestand tegen wat de kollomen omschrijft. Kunnen jullie mij hieraan helpen? 

 

Jip

**Comment by basvanbemmel** [comment]
email Wed 10/4/2023 10:52 AM


Hoi Marnix, Bas,
 
Bijgevoegd Zelfde table voor de aangepaste labour.dat bestanden. 


![image](https://github.com/ObjectVision/RSopen/assets/24241780/bde48c05-082b-4458-ab18-7a16248a2b18)

 
Kolom	Symbool	Beschrijving
1	z	LMS-subzone nummer
2	Ee	Aantal banen Industrie (IN)
3	“	Aantal banen Nijverheid (NY)
4	“	Aantal banen Transport (TR)
5	“	Aantal banen Overige consumentendiensten (OC)
6	“	Aantal banen Directe Consumentendiensten (DC)
7	“	Aantal banen Financiële en zakelijke diensten (FZ)
8	“	Aantal banen Detailhandel (DH)
9	“	Aantal banen Logistiek (LO)
10	“	Aantal banen Zorg (ZO)
11	“	Aantal banen Overheid en Onderwijs (OO)
12	“	Aantal banen Landbouw (LA)
10	 	Werkzame beroepsbevolking mannen
11	 	Werkzame beroepsbevolking vrouwen
 
Koppeling met oude sectoren (waren er 7, overheid en zorg was 1 sector) is: 
 	TIGRIS XL-sectoren (nieuw)	TIGRIS XL-sectoren (oud)	 
1	Industrie	Industrie en nijverheid	 
2	Nijverheid	Industrie en nijverheid	 
3	Transport	Logistiek	 
4	Consumentendiensten overig	Consumentendiensten	 
5	Consumentendiensten direct	Consumentendiensten	 
6	Financiële en zakelijke diensten	Zakelijke en financiele dienstverlening	 
7	Detailhandel	Detailhandel	 
8	Logistiek (Groothandel, e-shopping, reparatie)	Logistiek	 
9	Zorg	Overheid en zorg	 
10	Overheid en onderwijs	Overheid en zorg	 
11	Landbouw	Landbouw	 
 
Groet,
Barry
