### ISSUE TITLE
Vijf varianten inbouwen

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#49]
De (beleids)varianten hebben betrekking op de restricties, geschiktheden (incl ‘tredes’), plannen/‘stimuli’, dichtheden etc. (zie item: /VariantParameters). We draaien ze gecombineerd met de scenario’s. Ook deze heb ik al ingesteld. De varianten:

1. BAU: de business as usual variant (bestaand/trendmatig beleid, consistent met de planmonitor NOVI 2023 en te gebruiken voor alle vier de basisscenario’s: Hoog-3graden, Laag-3graden, Hoog-2graden, Laag-2graden).
2. WBS: een onzekerheidsverkenning o.b.v. de kamerbrief ‘water en bodem sturend’, uitgewerkt o.b.v. input van Deltares hieromtrent in het kader van RVNL**, alleen uit te werken in de context van Hoog-3graden.
3. Verdichting: een onzekerheidsverkenning met relatief veel verdichting (inbreiding) binnen regio’s, alleen uit te werken in de context van Hoog-3graden.
4. Uitleg: een onzekerheidsverkenning met juist veel uitleg binnen regio’s, alleen uit te werken in de context van Hoog-3graden.
5. Spreiding: een onzekerheidsverkenning met een bescheiden verschuiving van de groei naar hoog Nederland, alleen uit te werken in de context van Hoog-3graden.

**Comment by basvanbemmel** [comment]
Deze week is de naamgeving besproken dat is:

1)	HOOG SNEL: 2 graden
2)	HOOG VERTRAAGD: 3 graden
3)	LAAG SNEL
4)	LAAG VERTRAAGD 
5)	HOOG VERTRAAGD WBS: 3 graden D + C1+C2 WBS
6)	HOOG VERTRAAGD WBS: 3 graden D + C2 WBS

**Comment by basvanbemmel** [comment]
Scenario-lijst is geworden (naamgeving zoals in cfg):
BAU (=3 graden)
WBSA: alleen WLO-HOOG
WBSB: Alleen WLO-HOOG
Verdichting
Uitleg
