### ISSUE TITLE
Nieuwer LISA jaar toevoegen

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#50]
Nu zit LISA 2021 erin, heeft PBL al nieuwere?

**Comment by basvanbemmel** [comment]
Er is een nieuwere (2022) bij het PBL, Ik krijg dat deze week van HvA geanonimiseerd.

**Comment by basvanbemmel** [comment]
inmiddels geleverd

**Comment by jipclaassens** [comment]
Ik heb geen mail hierover ontvangen!

**Comment by basvanbemmel** [comment]
ik had als email jip.cl.... gedaan, inmiddels goed gegaan
