### ISSUE TITLE
WLO: batch werkend maken

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/RSopen#51]
Jip zou je kunnen zorgen dat de batch (https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/WLO2024/batch/RunAll.bat) weer werkt? Ik heb het gisteren eens aangezet in 14.10.1 maar het loopt vast op BaseData.

Zodra deze werkt zal ik op me nemen om te bijhouden of die blijft werken bij gewijzgde code.

Ik krijg nu op /MaakBasedata/Generate_Run2 (nieuw soort melding overigens nooit eerder gezien):

FailReason
UsingCache Error: Cannot find reference in Using = "CaseClassifications/Vastgoed/OP"
[[/BaseData/BAG_nieuwbouw/Result/Write]]
/BaseData/BAG_nieuwbouw/Result/Write/Generate 

![image](https://github.com/ObjectVision/RSopen/assets/24241780/10906250-6891-4c4f-a237-2f1f78d3f535)

**Comment by jipclaassens** [comment]
Als het goed is, is het nu gefixt

**Comment by basvanbemmel** [comment]
Bij mij werkt het nog niet, er zijn 2 problemen:
- bestand BAG_UitsmeerMatrix/Y2024.fss ontbreekt zowel in RSL als RSOpen (dus ik kon het ook niet kopieren). Is een probleem bij /MaakBasedata/Generate_Run2. Ik vermoed dat het in jouw working copy wel staat
- Ik heb iets vreemds geconstateerd (ook al eerder) met /SourceData/Infrastructuur/osm/NetworkPreperation/preperation/ExtraVerbindingen/ExtraBoatConnections/Duitsland/pointset
zijn de noordduitse bootverbindingen. Ik heb het gewijzigd in (maar nog niet gecommit), regel 66 in ExtraBoatConnections.dms:
			attribute<LambertEA> point_lea := point(pointcol(point_lea_src), pointrow(point_lea_src), LambertEA);
			attribute<rdc_meter> point := convert(point_lea,rdc_meter);
Echt een projectie dingetje (lag eerst ver de noordzee op richting schotland)

**Comment by jipclaassens** [comment]
Je hebt gelijk:
- Deze had ik nog niet gegenereerd. Staat aan en zal m comitten.
- Welke versie gebruik je? In 14.10.1 ziet het er namelijk zo uit:
![image](https://github.com/ObjectVision/RSopen/assets/48675272/e619e405-ccab-405a-8528-01f4d2cbd43d)
  En die convert zit er bij mij al in. Heb jij wel al de geupdatete versie binnengehaald?

**Comment by basvanbemmel** [comment]
14.1.0 ja voor de duidelijkheid ik heb de code dus gewijzgd (zoals aangegeven) omdat ik in de batch hier een foutmelding op kreeg. Batch ging nu verder maar toen kreeg ik het probleem onder punt 1.

**Comment by basvanbemmel** [comment]
ok top dank!

**Comment by basvanbemmel** [comment]
werkt helaas nog steeds niet met PD 10552 in 14.10.1 en RunAll.cmd. Na 10 a 15 minuten Probleem met:
/SourceData/Infrastructuur/osm/NetworkPreperation/preperation/ExtraVerbindingen/ExtraBoatConnections/Duitsland/pointset/point_lea_src

![image](https://github.com/ObjectVision/RSopen/assets/24241780/80470946-7f62-4754-b1a6-a8bb8217ea8e)

**Comment by basvanbemmel** [comment]
Oh nee het is een ander probleem /MaakBasedata/Generate_Run3 bestaat niet meer. ik zet het uit  in de batch

**Comment by basvanbemmel** [comment]
Er gaat iets nieuws fout zie screendumps onder

![image](https://github.com/ObjectVision/RSopen/assets/24241780/6f91f1e9-aa1d-4e1e-a3e7-6f8949cf811f)

![image](https://github.com/ObjectVision/RSopen/assets/24241780/c0d788d7-209d-4361-8fb1-a790bd131554)

**Comment by jipclaassens** [comment]
hm er zijn ook veel meer items in /MaakVariantData dan er in de batch worden aangeroepen... Dit is nieuw voor mij.

**Comment by jipclaassens** [comment]
Dit zou nu wel moeten werken!

**Comment by basvanbemmel** [comment]
ok dank ik ga het checken

**Comment by basvanbemmel** [comment]
werkt helaas nog steeds niet in 14.11.2 en in PD 10558, iets met verblijfsrecreatie bij BAU maar ook met verwijzing naar Y20230 terwijl alleen eindjaar op Y is geantwoord

[progress][[/SourceData/Infrastructuur/OSM/NetworkPreperation/preperation/ExtraVerbindingen/ExtraBoatConnections/Duitsland/pointset/point_lea_src]]

Item /MaakVariantData/Verblijfsrecreatie Not found
Item /MaakVariantData/Verblijfsrecreatie not found[memory]Highest Reserved in Blocks 3[MB]; Highest allocated: 0[MB]; Highest freed: 0[MB]; Highest uncommitted: 2[MB]; Highest PageFileUsage: 24[MB]
[progress]@@@@@ Logging ended for k:/PD/WLO2024/Runs/log.txt at 2024-02-13 07:58:40
[memory]Highest Reserved in Blocks 3[MB]; Highest allocated: 0[MB]; Highest freed: 0[MB]; Highest uncommitted: 2[MB]; Highest PageFileUsage: 24[MB]
Completed casus.dms /MaakVariantData/Verblijfsrecreatie ?
ERROR: updating of item /MaakVariantData/Verblijfsrecreatie in casus.dms failed.
batch will be aborted after pause because of a detected failure
Press any key to continue . . .

![image](https://github.com/ObjectVision/RSopen/assets/24241780/9ce17d28-f74f-454c-adfb-42bcc794b999)


![image](https://github.com/ObjectVision/RSopen/assets/24241780/b2387f1c-fc12-4f4c-9829-5c87859df637)

![image](https://github.com/ObjectVision/RSopen/assets/24241780/3dcc1a6f-25c6-4316-96ed-222457289d5b)

**Comment by jipclaassens** [comment]
Oeps, verblijfsrecreatie bestaat niet. Het is verblijfsrecreatieTrends.

Aangepast!

**Comment by basvanbemmel** [comment]
top! ik draai het gelijk even.

**Comment by basvanbemmel** [comment]
Nu nog dit probleem (we zijn er bijna volgens mij)

![image](https://github.com/ObjectVision/RSopen/assets/24241780/13425c56-2663-410c-9482-837443f0b536)

**Comment by jipclaassens** [comment]
Fixed een ding.
BIj mij draait de batch

**Comment by basvanbemmel** [comment]
Bij mij helaas niet, loopt op hetzelfde vast als vorige keer. ik draai exact PD10563 (geen enkele wijziging tov de server)

![image](https://github.com/ObjectVision/RSopen/assets/24241780/9e282682-c0fc-4783-b2b9-c5c12fa08674)

![image](https://github.com/ObjectVision/RSopen/assets/24241780/bd9785d3-f4b7-4c8b-aefe-4a8df19a3891)

**Comment by jipclaassens** [comment]
Heb je expliciete schrijfrechten op die map? Unable to commit data lijkt wellicht een windows/azure probleem?

@MaartenHilferink @mtbeek32 hebben jullie hier ervaring mee?

**Comment by basvanbemmel** [comment]
echt zeer onwaarschijnlijk ik heb nooit problemen gehad om op die K-schijf dingen weg te schrijven. Werkt wel in de GUI


![image](https://github.com/ObjectVision/RSopen/assets/24241780/d07341f5-c84c-4a75-bc5e-88d2e39d20f6)

**Comment by jipclaassens** [comment]
Hmm, vreemd. Ik heb het ook even aan collega's gevraagd. Vandaag een VU dag. ik zal morgen verder kijken

**Comment by basvanbemmel** [comment]
ok komt morgen wel,prima

**Comment by MaartenHilferink** [comment]
"Unable to commit data ..." volgt op alle situaties waarin de if in het midden hieronder in de else tak komt en er geen andere/eerdere fail reason was en geen suspension, bijvoorbeeld:
- DoWriteItem faalde (niet te verwerken file naam, disk full, etc.)
- Calculation was niet gescheduled (zou niet voor mogen komen)
- CurrRangeItem() was ergens door gefaald (bijvoorbeeld IntegrityCheck), maar this (nog) niet  (zou niet voor mogen komen)

![image](https://github.com/ObjectVision/RSopen/assets/2284361/27e90c6b-f805-4eec-b08c-4463a2385ab3)

Als je een reproduceerbaar voorbeeld hebt, kan ik hopelijk specifieker worden

**Comment by basvanbemmel** [comment]
ik krijg nu in 14.11.2 PD 10572 
/MaakBasedata/Generate_Run10 in PrepareBaseData.dms failed.

![image](https://github.com/ObjectVision/RSopen/assets/24241780/5141b57b-1b0c-4645-98e3-5ec05b11cadd)

Als ik dit met de hand run in de GUI werkt het wel. ALs ik vervolgens de batch verder run met VariantData krijg ik  weer de melding zoals beschreven in:
https://github.com/ObjectVision/RSopen/issues/51#issuecomment-1943616543

Ik heb in Templates/Zeef.dms regel 26 ook geprobeerd de IntegrityCheck uit te zetten maar biedde geen soelaas

	attribute<bool> ReadProtoBeschikbaar_AdminDomain  (AdminDomain) := ReadProtoBeschikbaar_AdminDomain_UNCHECKED, IntegrityCheck = "not(all(IsNull(this))) && not(all(IsZero(this)))";

Ik heb wel het idee dat het daar ergens misgaat.

oplossing 1:
"DoWriteItem faalde (niet te verwerken file naam, disk full, etc.)"
lijkt mij wel uitgesloten eigenlijk, geen lange vreemde filenaam, voldoende diskruimte en andere sectoren worden wel weggeschreven wind.fss ed.

**Comment by jipclaassens** [comment]
![image](https://github.com/ObjectVision/RSopen/assets/48675272/3383a915-5d4f-4490-b68d-6a0f53630024)

**Comment by basvanbemmel** [comment]
ok mooi, ik had net ook nog een dingetje gecommit aangaande  GWV_2020_buffer_FULL_FLAT_PLANAR_NONE_EPSG_28992
projectiedingetje.

Ik ben vandaag veders niet aan het werk overigens

**Comment by jipclaassens** [comment]
Okee, het modle moet natuurlijk nog op allerlei plekken worden geupdatet met oa jouw aanpassngen uit PM24 denk ik?

Maar ik heb alle technische fixes/updates uit PM24 overgezet.

**Comment by basvanbemmel** [comment]
klopt ja, voor nu even het belangrijkst dat het technisch werkt ja. Dank
