### ISSUE TITLE
Planmonitor 2024: standaard diameter gebruikt voor windturbine ipv diameter uit veldsituatie bestand

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/RSopen#53]
Bij het updaten van het windturbinebestand voor de veldsitutie kwam ik erachter dat ook in het het nu gebruikte windturbinebestand (/SourceData/Energie/Wind/Veldsituatie_2021) de diameter niet gebruikt wordt /SourceData/Energie/Wind/Veldsituatie_2021/Punten/Diameter
in het bepalen van de windrestrictie rond een windturbine
/Analysis/Wind_restricties/Dynamisch/bestaande_turbines/geometry_buffer

het komt uit /Analysis/WindTurbineType/RotorDiameter

ik was eigenlijk altijd in de veronderstelling dat het diameter-veld uit het bestand werd gebruikt. Lastige is dat in het template PointBuffer de tweede template argument een parameter is en geen attribute.

Is dit makkelijk op te lossen?

**Comment by jipclaassens** [comment]
Het is geimplementeerd en gecommit. Maar hiervoor heb je wel 14.10.2 or 15.0.0 nodig. En deze wordt waarschijnlijk maandag gepubliceerd. Dus als je deze wijziging binnenhaalt werkt het nog niet bij jou. Je kunt ook de oude variant nog even aanzetten.

![image](https://github.com/ObjectVision/RSopen/assets/48675272/67259455-41c5-47a4-ab3b-a7f3e4a0adf5)

**Comment by basvanbemmel** [comment]
ok prima, ook top!
