### ISSUE TITLE
Planmonitor2024: batch werkend maken voor alle zichtjaren

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/RSopen#54]
Ik heb nu de batch werkend (met PD 10573 en geodms 14.11.2) voor in een keer naar Y2050 ook met de nieuwe veldsituatie windturbines 2024, ik heb geconstateerd dat dit effect heeft overigens.

Voor runnen met alle zichtjaren krijg nu echter:

![image](https://github.com/ObjectVision/RSopen/assets/24241780/6437501d-ad6f-4616-a072-8b77f9a7ca07)

Y2030 wordt wel geheel berekend

**Comment by basvanbemmel** [comment]
Nog steeds een probleem in PlanMonitor2024 PD1029 met 14.13.2
![PlanMonitor2024_PD1029_exe14_13_2](https://github.com/ObjectVision/RSopen/assets/24241780/0a03b1bc-2efe-4041-82b1-9769df33df8d)

In GUI (na zetten op regel 4:
	parameter<bool>                         AlleenEindjaar                   := false;
in Modelparamters.dms

/Analysis/Allocatie/Zichtjaren/Y2040/impl/CalcStand/Subsector_rel
Run up to Causa Prima
/Analysis/Allocatie/Zichtjaren/Y2040/Sequences/Seq_0/SectorAllocRegios/Wonen_NVM/Iters_Normaal/Iter_0/Subsectoren/eengezins_VrijeSector/AdminDomain/Beschikbaar

![image](https://github.com/ObjectVision/RSopen/assets/24241780/303b6d41-f8d0-429e-9fc5-b5e8b00238ce)

Y2030 ziet er overigens globaal wel goed uit subsector_rel beetje 1/3 van tov (oude) Y2050 resultaat

**Comment by basvanbemmel** [comment]
Dit heeft wel hoge prio overigens.

**Comment by jipclaassens** [comment]
![image](https://github.com/ObjectVision/RSopen/assets/48675272/ac2cfaf6-30cf-48ba-ab69-1e95bb66817c)

@basvanbemmel  Kun jij mij de privdata sturen?

**Comment by basvanbemmel** [comment]
en enkel de ontkoppelde fss-bestanden leveren  voldoet dat ook?
