### ISSUE TITLE
union_unit en data lukt niet

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/RSopen#55]
Ik wil graag in de GeoDMS de NOVEX woningbouwlocaties aanpassen voor de geometrie met plannaam Utrecht ZuidWest
Daar wil ik dat bepaalde stukken (CBS BBG 2017 code bouwterrein en overig agrarisch terrein) overblijven.
op zich is dat gelukt.
zie: /SourceData/Beleid2024/Plancapaciteit/Wonen/NOVEX/bebouwbaar/bebouwbaar

ik wil deze samenvoegen met 
/SourceData/Beleid2024/Plancapaciteit/Wonen/NOVEX/woningbouwlocaties_excl_Utrecht/geometry

GeoDMS 14.11.2
PD 10575: https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/PlanMonitor2024
SD 10569 https://pbl.sliksvn.com/ruimtescanner/PBL/SourceData/Trunk/RSL

Gaat om 
item om het samen te voegen
/SourceData/Beleid2024/Plancapaciteit/Wonen/NOVEX/woningbouwlocaties_incl_Utrecht/geom

probleem is dat de parameter (/SourceData/Beleid2024/Plancapaciteit/Wonen/NOVEX/bebouwbaar/bebouwbaar_union) geen unit heeft,.

![image](https://github.com/ObjectVision/RSopen/assets/24241780/5d1bc4c5-9d45-42b8-80f1-c80b842abc2a)

**Comment by mtbeek32** [comment]
Bas,

Voor een parameter configureer je inderdaad geen domain unit, maar soms moet je expliciet naar een domain unit verwijzen. Gebruik dan als domain unit: **void**. 

Dit gebruik je bijvoorbeeld als je een set van parameters maakt met een for_each_nedv functie.
	
Voor jouw voorbeeld kun je ook gebruiken maken van de constructie met een void domain, zie onderstaande configuratie:

```
container Union_Unit_Data
{
   unit<uint32> src: nrofrows = 2
   {
      attribute<.> id := id(.);
   }
   parameter<uint32> id_param := 10;
	
   unit<uint32> src_param := union_unit(src, void)
   {
      attribute<uint32> id := union_data(., src/id, id_param);
   }
}
```

**Comment by basvanbemmel** [comment]
ach natuurlijk void!
Is dat eigenlijk iets wat wel goed terugkomt in de doc als je met een parameter werkt?

**Comment by mtbeek32** [comment]
Inmiddels ook opgenomen in de documentatie, zie: https://github.com/ObjectVision/GeoDMS/wiki/Union_unit

**Comment by basvanbemmel** [comment]
ok top!
