### ISSUE TITLE
Planmonitor2024: WMTS met satellietbeelden?

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/RSopen#56]
Ik zie in de ngr_layer.dms nu een verwijzing naar een topkaart:
service.pdok.nl/brt/achtergrondkaart/wmts/v2_0

Is er ook een WMTS met satellietbeelden. Ik meen in oude cfg's dat wel eens te heben gezien maar kan dat niet meer vinden.
Satellietbeelden zijn handig bij interpreteren met gebieden met bijvoorbeeld plancapaciteit.

**Comment by mtbeek32** [comment]
Werkende link voor een luchtfoto:

https://service.pdok.nl/hwh/luchtfotorgb/wmts/v1_0?layer=Actueel_orthoHR&style=default&tilematrixset=EPSG%3A28992&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image%2Fpng&TileMatrix=05&TileCol=15&TileRow=15

@Erik zou jij dit kunnen testen en de resulterende code hier kunnen posten.

**Comment by eoudejans** [comment]
Valid background layer ngr_layer.dms dms config:
```
////////////////////////////////////////////////////////////////////////////////////////
//                                                                                    //
//                                                                                    //
//        Configuratie voor WMS lagen, gedefineerd vanuit een opgevraagd              //
//        GetCapabilities Request in xml format.                                      //
//                                                                                    //
//                              Object Vision 2023                                    //
//                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////

container ngr_layer {

	parameter<uint32> nr_att := 8;
	parameter<uint32> nr_row := 15;
	
	unit<uint32> TileMatrixElems := range(uint32, 0, nr_att * nr_row)
	{
		attribute<string> values:
		//name          , ScaleDen , Top        , Left     ,Width ,Height, MatrixWidth,MatrixHeight
		[
		 'EPSG:28992:0' ,'12288000','-285401.92','903402.0','256' ,'256' ,    '1'     ,    '1'
		,'EPSG:28992:1' , '6144000','-285401.92','903402.0','256' ,'256' ,    '2'     ,    '2'
		,'EPSG:28992:2' , '3072000','-285401.92','903402.0','256' ,'256' ,    '4'     ,    '4'
		,'EPSG:28992:3' , '1536000','-285401.92','903402.0','256' ,'256' ,    '8'     ,    '8'
		,'EPSG:28992:4' ,  '768000','-285401.92','903402.0','256' ,'256' ,   '16'     ,   '16'
		,'EPSG:28992:5' ,  '384000','-285401.92','903402.0','256' ,'256' ,   '32'     ,   '32'
		,'EPSG:28992:6' ,  '192000','-285401.92','903402.0','256' ,'256' ,   '64'     ,   '64'
		,'EPSG:28992:7' ,   '96000','-285401.92','903402.0','256' ,'256' ,  '128'     ,  '128'
		,'EPSG:28992:8' ,   '48000','-285401.92','903402.0','256' ,'256' ,  '256'     ,  '256'
		,'EPSG:28992:9' ,   '24000','-285401.92','903402.0','256' ,'256' ,  '512'     ,  '512'
		,'EPSG:28992:10',   '12000','-285401.92','903402.0','256' ,'256' , '1024'     , '1024'
		,'EPSG:28992:11',    '6000','-285401.92','903402.0','256' ,'256' , '2048'     , '2048'
		,'EPSG:28992:12',    '3000','-285401.92','903402.0','256' ,'256' , '4096'     , '4096'
		,'EPSG:28992:13',    '1500','-285401.92','903402.0','256' ,'256' , '8192'     , '8192'
		,'EPSG:28992:14',     '750','-285401.92','903402.0','256' ,'256' ,'16384'     ,'16384'
		];
	}

	unit<uint32> TileMatrix := range(uint32, 0, nr_row)
	{
		attribute<.>       id                := id(.);

		attribute<string>  name              :=         TileMatrixElems/values[value(id * nr_att + 0, TileMatrixElems)];
		attribute<float64> ScaleDenominator  := float64(TileMatrixElems/values[value(id * nr_att + 1, TileMatrixElems)]);
		attribute<float64> LeftCoord         := float64(TileMatrixElems/values[value(id * nr_att + 2, TileMatrixElems)]);
		attribute<float64> TopCoord          := float64(TileMatrixElems/values[value(id * nr_att + 3, TileMatrixElems)]);
		attribute<uint16>  TileWidth         :=  uint16(TileMatrixElems/values[value(id * nr_att + 4, TileMatrixElems)]);
		attribute<uint16>  TileHeight        :=  uint16(TileMatrixElems/values[value(id * nr_att + 5, TileMatrixElems)]);
		attribute<uint32>  MatrixWidth       :=  uint32(TileMatrixElems/values[value(id * nr_att + 6, TileMatrixElems)]);
		attribute<uint32>  MatrixHeight      :=  uint32(TileMatrixElems/values[value(id * nr_att + 7, TileMatrixElems)]);
	}

	parameter<string> layer_src  := 'Actueel_orthoHR';

	parameter<string> image_format := 'png';
	parameter<string> host   := 'service.pdok.nl';

	parameter<string> target := 'hwh/luchtfotorgb/wmts/v1_0' //'/brt/achtergrondkaart/wmts/v2_0'
		'?SERVICE=WMTS'
		'&REQUEST=GetTile'
		'&VERSION=1.0.0'
		'&LAYER=' + layer_src + 
		'&TILEMATRIXSET=EPSG:28992' +
		'&style=default'
		'&TILEMATRIX=@TM@'
		'&TILEROW=@TR@'
		'&TILECOL=@TC@'
		'&FORMAT=image/' + image_format
	;
}
```

Resulting in the following request:
https://service.pdok.nl/hwh/luchtfotorgb/wmts/v1_0?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=Actueel_orthoHR&TILEMATRIXSET=EPSG:28992&style=default&TILEMATRIX=6&TILEROW=32&TILECOL=32&FORMAT=image/png

But unfortunately results in the following error: "on_read:stream truncated":

![image](https://github.com/ObjectVision/RSopen/assets/96182097/8eb990b0-f6d6-455d-9c8f-17a0189e16b9)

To be further investigated why this layer gets truncated on read.

**Comment by basvanbemmel** [comment]
Ok alvast dank voor de moeite! Wellicht kijken bij 2UP hoe dat gedaan is?


container wms_layer_llh {
	parameter<uint32> nr_att := 8;
	parameter<uint32> nr_row := 16;
	
	unit<uint32> TileMatrixElems := range(uint32, 0, nr_att * nr_row)
	{
		attribute<string> values:
		//name          , ScaleDen ,             Left     , Top     ,Width ,Height, MatrixWidth,MatrixHeight
		[
		 'EPSG:4326:0' , '279541132.0143589',      '-180.0', '90.0', '256' ,'256' ,       '2'     ,       '1'
		,'EPSG:4326:1' , '139770566.00717944',     '-180.0', '90.0', '256' ,'256' ,       '4'     ,       '2'
		,'EPSG:4326:2' ,  '69885283.00358972',     '-180.0', '90.0', '256' ,'256' ,       '8'     ,       '4'
		,'EPSG:4326:3' ,  '34942641.50179486',     '-180.0', '90.0', '256' ,'256' ,      '16'     ,       '8'
		,'EPSG:4326:4' ,  '17471320.75089743',     '-180.0', '90.0', '256' ,'256' ,      '32'     ,      '16'
		,'EPSG:4326:5' ,   '8735660.375448715',    '-180.0', '90.0', '256' ,'256' ,      '64'     ,      '32'
		,'EPSG:4326:6' ,   '4367830.1877243575',   '-180.0', '90.0', '256' ,'256' ,     '128'     ,      '64'
		,'EPSG:4326:7' ,   '2183915.0938621787',   '-180.0', '90.0', '256' ,'256' ,     '256'     ,     '128'
		,'EPSG:4326:8' ,   '1091957.5469310894',   '-180.0', '90.0', '256' ,'256' ,     '512'     ,     '256'
		,'EPSG:4326:9' ,    '545978.7734655447',   '-180.0', '90.0', '256' ,'256' ,    '1024'     ,     '512'
		,'EPSG:4326:10',    '272989.38673277234',  '-180.0', '90.0', '256' ,'256' ,    '2048'     ,    '1024'
		,'EPSG:4326:11',    '136494.69336638617',  '-180.0', '90.0', '256' ,'256' ,    '4096'     ,    '2048'
		,'EPSG:4326:12',     '68247.34668319309',  '-180.0', '90.0', '256' ,'256' ,    '8192'     ,    '4096'
		,'EPSG:4326:13',     '34123.67334159654',  '-180.0', '90.0', '256' ,'256' ,   '16384'     ,    '8192'
		,'EPSG:4326:14',     '17061.83667079827',  '-180.0', '90.0', '256' ,'256' ,   '32768'     ,   '16384'
		,'EPSG:4326:15',      '8530.918335399136', '-180.0', '90.0', '256' ,'256' ,   '65536'     ,   '32768'
		];
	}

	unit<uint32> TileMatrix := range(uint32, 0, nr_row)
	{
		attribute<.>       id                := id(.);

		attribute<string>  name              :=         TileMatrixElems/values[value(id * nr_att + 0, TileMatrixElems)];
		attribute<float64> ScaleDenominator  := float64(TileMatrixElems/values[value(id * nr_att + 1, TileMatrixElems)]);
		attribute<float64> LeftCoord         := float64(TileMatrixElems/values[value(id * nr_att + 2, TileMatrixElems)]);
		attribute<float64> TopCoord          := float64(TileMatrixElems/values[value(id * nr_att + 3, TileMatrixElems)]);
		attribute<uint16>  TileWidth         :=  uint16(TileMatrixElems/values[value(id * nr_att + 4, TileMatrixElems)]);
		attribute<uint16>  TileHeight        :=  uint16(TileMatrixElems/values[value(id * nr_att + 5, TileMatrixElems)]);
		attribute<uint32>  MatrixWidth       :=  uint32(TileMatrixElems/values[value(id * nr_att + 6, TileMatrixElems)]);
		attribute<uint32>  MatrixHeight      :=  uint32(TileMatrixElems/values[value(id * nr_att + 7, TileMatrixElems)]);
	}

	parameter<string> host   := 'tiles.geoservice.dlr.de';
	//parameter<string> layer  := 'hillshade';
	//parameter<string> layer  := 'eoc:litemap';
	parameter<string> layer := 'eoc:basemap';
	//parameter<string> url  := 'https://' + host + '/service/wmts'; //https://geodata.nationaalgeoregister.nl/wmts/;
	parameter<string> url    := 'https://' + host;
	parameter<string> unit   := "degree";

	// https://tiles.geoservice.dlr.de/service/wmts?REQUEST=GetCapabilities
	parameter<string> target := 
		'/service/wmts/?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&LAYER=' + layer +
		'&STYLE=_empty&TileMatrixSet=EPSG%3A4326&TILEMATRIX=EPSG%3A4326%3A@TM@'+
		'&TILEROW=@TR@&TILECOL=@TC@&FORMAT=image%2Fpng';
}

**Comment by eoudejans** [comment]
Werkende wmts achtergrond configuratie voor de 25 centimeter actuele ortho luchtfoto:

```cpp
[////////////////////////////////////////////////////////////////////////////////////////
//                                                                                    //
//                                                                                    //
//        Configuratie voor WMS lagen, gedefineerd vanuit een opgevraagd              //
//        GetCapabilities Request in xml format.                                      //
//                                                                                    //
//                              Object Vision 2018                                    //
//                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////

container ngr_layer {

 parameter <uint32> nr_att :=  8;
  parameter <uint32> nr_row := 15;

  unit<uint32> TileMatrixEl := range(uint32, 0, nr_att * nr_row)
   {
      attribute<string> values:      
        //name         , ScaleDen    , Top        , Left      ,Width ,Height , MatrixWidth, MatrixHeight
      [
        'EPSG:28992:0' ,'12288000'   ,'-285401.92', '903402.0', '256' ,'256' ,    '1'  ,    '1'
       ,'EPSG:28992:1' , '6144000'   ,'-285401.92', '903402.0', '256' ,'256' ,    '2'  ,    '2'
       ,'EPSG:28992:2' , '3072000'   ,'-285401.92', '903402.0', '256' ,'256' ,    '4'  ,    '4'
       ,'EPSG:28992:3' , '1536000'   ,'-285401.92', '903402.0', '256' ,'256' ,    '8'  ,    '8'
       ,'EPSG:28992:4' ,  '768000'   ,'-285401.92', '903402.0', '256' ,'256' ,   '16'  ,   '16'
       ,'EPSG:28992:5' ,  '384000'   ,'-285401.92', '903402.0', '256' ,'256' ,   '32'  ,   '32'
       ,'EPSG:28992:6' ,  '192000'   ,'-285401.92', '903402.0', '256' ,'256' ,   '64'  ,   '64'
       ,'EPSG:28992:7' ,   '96000'   ,'-285401.92', '903402.0', '256' ,'256' ,  '128'  ,  '128'
       ,'EPSG:28992:8' ,   '48000'   ,'-285401.92', '903402.0', '256' ,'256' ,  '256'  ,  '256'
       ,'EPSG:28992:9' ,   '24000'   ,'-285401.92', '903402.0', '256' ,'256' ,  '512'  ,  '512'
       ,'EPSG:28992:10',   '12000'   ,'-285401.92', '903402.0', '256' ,'256' , '1024'  , '1024'
       ,'EPSG:28992:11',    '6000'   ,'-285401.92', '903402.0', '256' ,'256' , '2048'  , '2048'
       ,'EPSG:28992:12',    '3000'   ,'-285401.92', '903402.0', '256' ,'256' , '4096'  , '4096'
       ,'EPSG:28992:13',    '1500'   ,'-285401.92', '903402.0', '256' ,'256' , '8192'  , '8192'
       ,'EPSG:28992:14',     '750'   ,'-285401.92', '903402.0', '256' ,'256' ,'16384'  ,'16384'
     ] ;
   }
    unit<uint32> TileMatrix := range(uint32, 0, nr_row)
   {
      attribute<.>       id               := id(.);
      attribute<string>  name             := TileMatrixEl/values[value(id * nr_att + 0, TileMatrixEl)];
      attribute<float64> ScaleDenominator := float64(TileMatrixEl/values[value(id * nr_att + 1, TileMatrixEl)]);
      attribute<float64> LeftCoord        := float64(TileMatrixEl/values[value(id * nr_att + 2, TileMatrixEl)]);
      attribute<float64> TopCoord         := float64(TileMatrixEl/values[value(id * nr_att + 3, TileMatrixEl)]);
      attribute<uint16>  TileWidth        :=  uint16(TileMatrixEl/values[value(id * nr_att + 4, TileMatrixEl)]);
      attribute<uint16>  TileHeight       :=  uint16(TileMatrixEl/values[value(id * nr_att + 5, TileMatrixEl)]);
      attribute<uint32>  MatrixWidth      :=  uint32(TileMatrixEl/values[value(id * nr_att + 6, TileMatrixEl)]);
      attribute<uint32>  MatrixHeight     :=  uint32(TileMatrixEl/values[value(id * nr_att + 7, TileMatrixEl)]);
   }

    parameter<string> layer  := 'Actueel_ortho25';

    parameter<string> image_format := 'jpeg';
    parameter<string> host := 'service.pdok.nl';

    parameter<string> target := '/hwh/luchtfotorgb/wmts/v1_0'
       '?SERVICE=WMTS'
       '&REQUEST=GetTile'
       '&VERSION=1.0.0'
       '&LAYER=' + layer +
       '&TILEMATRIXSET=EPSG:28992'
       '&TILEMATRIX=@TM@'
       '&TILEROW=@TR@'
       '&TILECOL=@TC@'
       '&FORMAT=image/'+image_format
  ;
```

![image](https://github.com/ObjectVision/RSopen/assets/96182097/a40b9a01-8f81-4e13-83d3-8194ff7c7988)

**Comment by eoudejans** [comment]
Belangrijkste aanpassing is het bestandstype aanpassen naar jpeg.

**Comment by basvanbemmel** [comment]
Werkt! Klasse

![image](https://github.com/ObjectVision/RSopen/assets/24241780/d12d1f36-ddcb-4843-8e5f-34631cf281b0)
