### ISSUE TITLE
PM24: Wordt de windrestrictie wel goed meegenomen?

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/RSopen#57]
PM24
/Analysis/Wind_restricties/IsNietToegestaan

Er worden windmolen op de snelweg en in restrictief gebied geplaatst?

![image](https://github.com/ObjectVision/RSopen/assets/24241780/99a3eb80-8383-4ab3-8cc9-a623d85de46f)

**Comment by jipclaassens** [comment]
Het wordt goed meegenomen. Maar als je geen snelwegen wilt moet dit anders ingesteld worden... We kunnen hier snelwegen aan toevoegen?

`/VariantParameters/ReedsBenut/Wind/BuitenPlancapaciteit/BAU`

![image](https://github.com/ObjectVision/RSopen/assets/48675272/7e976e97-9215-45f4-a93e-b55a6b40a292)

**Comment by jipclaassens** [comment]
@basvanbemmel  
Wil je de reeds benut aanpassen? Dit is een inhoudelijke vraag en technische vraag. Dus dit issue kan gesloten worden. Alleen de inhoudelijke actie blijft dan voor jou staan. Akkoord?

**Comment by jipclaassens** [comment]
@basvanbemmel ik heb nu autowegen uit de BGT met een 25m buffer toegevoegd

**Comment by basvanbemmel** [comment]
is prima
