### ISSUE TITLE
PM24: /ModelParameters/WindmolenAfschrijving werkt niet

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/RSopen#63]
Ik heb /ModelParameters/WindmolenAfschrijving op 100 jaar gezet. 
Ik zie echter dat de reeds bestaande windturbines verdwijnen zie screendump.

Zwart: /Analysis/Allocatie/Zichtjaren/Y2050/impl/ReadStandWind/WindPolygoon/polydomain2/point_rdc
Groen: /SourceData/Energie/Wind/Veldsituatie_2024/Punten/geometry

PD10801: https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/PlanMonitor2024  + /ModelParameters/WindmolenAfschrijving op 100
GeoDMS: 14:14.0

/Analysis/Allocatie/Zichtjaren/Y2030/StateVoorAllocatie/Wind/jaartal_ingebruikname lijkt wel in orde

![image](https://github.com/ObjectVision/RSopen/assets/24241780/42f59ac4-4963-42a5-b4cf-d7f31b4b505f)

**Comment by jipclaassens** [comment]
@basvanbemmel dit is toch helemaal wenselijk? Allocatie resultaat gaat enkel over nieuwe ontwikkelingen. Oftewel, als je de afschrijvingstijd op 100 jaar zet. Blijven ze staan, dus onveranderd. Dus niet zichtbaar in de subsector_rel...

**Comment by basvanbemmel** [comment]
Je hebt gelijk inderdaad, op de een of andere wijze dacht ik dat het de stand weergeeft. (kan ik wel zelf maken). Wel gek dat nieuwe windturbines vlak bij bestaande staan, zie screendump



![image](https://github.com/ObjectVision/RSopen/assets/24241780/15a25876-1cd8-4e0c-9a31-e00fd212bbff)

**Comment by jipclaassens** [comment]
Oke, dat is niet goed. Ik zal er morgen naar kijken.

**Comment by jipclaassens** [comment]
De proximity buffer was te klein, dit is nu wel netjes 4x de rotor diameter.
