### ISSUE TITLE
PM24: Produktierun dynamisch itereren werkt niet

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/RSopen#64]
Ik heb eens getest of een produktierun werkt.  Gaat helaas fout op dynamisch itereren heb ik het idee.

GeoDMS 14.14.0
PD10812: https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/PlanMonitor2024

/Analysis/Allocatie/Zichtjaren/Y2030/Sequences/Seq_1/SectorAllocRegios/Wind_Provincie/Iters_Normaal/DetermineLastIter/StoppedIter nr_OrgEntity
![image](https://github.com/ObjectVision/RSopen/assets/24241780/9314567c-41ae-4c47-af6b-6227d38a8aa6)

![image](https://github.com/ObjectVision/RSopen/assets/24241780/3507a818-4116-4d7b-bf9c-c5fb63401c35)

**Comment by jipclaassens** [comment]
Dit vereist flink wat denk werk en is niet heel relevant nu. Ik heb het nu uitgezet.
Als je genoeg iters/sequencies hebt. Bijv 10 iters en 3 sequenties zal het geen probleem zijn.

Dan kun je iig verder.

**Comment by basvanbemmel** [comment]
Ok voor nu niet belangrijk, maar even pragmatisch/concreet produktierun kan dus niet gedraaid (in batch) worden? Moet ik je antwoord zo interpreteren.

**Comment by jipclaassens** [comment]
Jawel, dan worden ook gelijk base en variant date gemaakt, plus tussen jaren, plus juiste wind stempels.
