### ISSUE TITLE
PM24: Template Grid2VectorT werkt niet meer sinds 10754 (MAJOR UPDATE) 

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/RSopen#65]
Helaas werkt het /Templates/Grid2VectorT niet meer sinds 10754 (MAJOR UPDATE) 

wordt gebruikt in de planmonitor o.a. bij
/Planmonitor2024/KwetsbareWaarden/Waterveiligheid/IsKwetsbaar_geom
Wel precies wat we nu nodig hebben. Ik heb geprobeerd om het gisteren op te lossen maar lukt mij niet.

**Comment by basvanbemmel** [comment]
![image](https://github.com/ObjectVision/RSopen/assets/24241780/cb3e2ad3-d77f-4f8f-9bb8-85eb90396681)

**Comment by jipclaassens** [comment]
Er werd een subset gemaakt van het grid domein (deze was spoint en nu ipoint), resultaat daarvan was uint32 en nu uint64. 
Ik heb de select_uint32_with_org_rel van gemaakt. Dan werkt ie altijd.
