### ISSUE TITLE
Onverklaarbare werk allocatie in Rotterdam Zuid

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#67]
Er is veel meer werk ontwikkeling in Rotterdam zuid tussen revisie 10731 en 10754. 

Onderzoeksrichting:
- twee kopieren van cfg maken, van elke revisie apart. 
- run voor beide de base en variant data.
- vergelijk StartState/Werken tussen beide versies (`/BaseData/StateBasisjaar/read/Werken/Nijverheid`). Evt Total hiervan maken.
- vergelijk Beschikbaarheid tussen beide versies (`/Analysis/Zeef/Y2030/SectorXSubSectoren/Werken/Nijverheid/Beschikbaar`). Evt Total hiervan maken.
- Als deze beide weinig verschillen laten zien door naar de BagNieuwbouw resultaten (`/Analysis/Allocatie/StartState_metBAGnieuwbouw/Werken/Nijverheid`)
- Als deze weinig verschillen laat zien, door naar de allocatie.
- Eerste werk sector iter resultaat bekijken (`/Analysis/Allocatie/Zichtjaren/Y2030/Sequences/Seq_0/SectorAllocRegios/Werken_NVM/Iters_Normaal/Iter_0/IsNuGealloceerd`)

**Comment by basvanbemmel** [comment]
V10754
![image](https://github.com/ObjectVision/RSopen/assets/24241780/21ef35aa-78cd-4566-a95c-3934f047e21d)

V10731
![image](https://github.com/ObjectVision/RSopen/assets/24241780/c0e8ad1d-4d27-44d3-a68f-d4910ef1e1f2)

**Comment by jipclaassens** [comment]
v10731 reed benut:
![image](https://github.com/ObjectVision/RSopen/assets/48675272/f9efc24e-f052-4629-bcf8-93c9d4b995f4)

v10754
![image](https://github.com/ObjectVision/RSopen/assets/48675272/c63dda97-4596-4d76-bbbc-16661e8f181c)

**Comment by jipclaassens** [comment]
Reden:

- evident benut BGT is beter toegepast tussen deze revisies, zodat oa vliegvelden niet worden volgebouwd:
![image](https://github.com/ObjectVision/RSopen/assets/48675272/38a2365a-f8cd-4111-9b2f-5b82bfd05519)

- hierdoor zijn er veel minder plekken beschikbaar binnen de bestaande stad/agglomeratie. Hierdoor wordt nieuwe bebouwing naar buiten gedrukt. En eventueel zelfs overgeheveld naar corop.

**Comment by basvanbemmel** [comment]
Jip: je hoeft hier niets mee te doen is enkel ter vastlegging

/Analysis/Allocatie/Zichtjaren/Y2050/Sequences/Seq_2/SectorAllocRegios/Werken_NVM/Iters_Normaal/Iter_9/ClaimRealisatie/Werken
PD10848

![image](https://github.com/ObjectVision/RSopen/assets/24241780/5c22a81e-389e-4d1b-b13b-24c23ce84cce)

**Comment by basvanbemmel** [comment]
Uitdrukkelijke wens van Rienk om de claim niet te wijzigen tov de planmonitor 2023 (cfg PD9802 RSLight2021_ontwikkel_3_PlanMonitor2023) in deze cfg. Als er koppeling is met LISA op de een of andere wijze zou LISA dus eigenlijk niet geupdate moeten worden.

**Comment by jipclaassens** [comment]
Zoals in #27 beschreven staat, is vanuit de Ruimtescanner een export gemaakt van de stand in het basisjaar van werken en wonen. Deze worden gebruikt om tigris mee te synchroniseren. Maar als vervolgens blijkt dat er in de afgelopen 5 jaar ontwikkelingen zijn geweest die TIGRIS 'fout' heeft voorspeld betekent dat niet dat we dat moeten negeren lijkt me. Ik neem aan dat de daadwerkelijke waarnemingen belangrijker zijn dan de modelprognoses?

**Comment by basvanbemmel** [comment]
volgens mij is het gat kleiner, PM23 maakt gebruikt van LISA21 en claims die 7 oktober 2022 zijn ingevoerd (met als bestandsnaam TXL_20221006), of die claims 2022 respresenteren weet ik niet
log commkit 9157:
- nieuwe claims woinen en werken uit Tigris XL ingelezen vanuit scenario Hoog (WLO). Vijfde en definitieve schot.

Ik zal het nog even zo laten, wil er nog even over nadenken.  1.3 Claimrealisatie voor Brielle in startsituatie (je begint dus al te hoog) vind voor nu nog acceptabel.
