### ISSUE TITLE
PM24: dist2 probleem in 14.14.0

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/RSopen#69]
Ik krijg een bug op:
/Planmonitor2024/KwetsbareWaarden/NatuurBuffer/kernel_buffer_40_cells/dist

dist2 Error: Cannot find operator for these arguments:
arg1 of type DataItem<IPoint>
arg2 of type Unit<UInt32>
Possible cause: argument type mismatch. Check the types of the used arguments.

![image](https://github.com/ObjectVision/RSopen/assets/24241780/8331777c-309e-4369-8a3f-1a5425b0e3e6)

**Comment by jipclaassens** [comment]
fixed

**Comment by basvanbemmel** [comment]
dat is echt snel dank!
