### ISSUE TITLE
Vergelijk resultaten RSopen en RSow3 variant BAU_ZP

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#7]
- Wat is het effect van de alternatieve LISA benadering?
- Wat is het effect van geen plan capaciteit?

**Comment by basvanbemmel** [comment]
Ik heb BAU kunnen runnen ik ga zo kijken. Afonderlijk effect plancap en LISA is natuurlijk wel lastig zonder verdere uitleg

**Comment by basvanbemmel** [comment]
![RSOPEN_BAU_2050_versus_RSLIGHT2021_ONTWIKKEL_3_BAUZP_2050](https://github.com/ObjectVision/RSopen/assets/24241780/4181747b-f80e-445b-b553-a6a537db5d72)

Helaas een enorm verschil. Dit is wel iets om verder uit te zoeken. Hoe kan het dat er ineens zo weinig wordt weggezet in RSOpen

**Comment by basvanbemmel** [comment]
@Jip zou jij wellicht eens kunnen kijken naar de claimrealisatie in RSOpen?

**Comment by jipclaassens** [comment]
Wow, rode vla. Ik ga t uitzoeken.

**Comment by jipclaassens** [comment]
Hoog BAU RSopen:



![Image](https://github.com/ObjectVision/RSopen/assets/48675272/ce74a8c7-128c-4cad-ad24-216625aabbec)

wonen lijkt gelijk aan Bas zn dump, de andere sectoren gaan helemaal mis...

**Comment by basvanbemmel** [comment]
Kreeg in het weekend de volgende melding bij het draaien van de batch (versie 0688f5e):
Er is niets in de Allocatie-map weggeschreven (Basedata en Variantdata wel in orde)

![image](https://github.com/ObjectVision/RSopen/assets/24241780/98248b4f-6eaa-44b7-b4d3-9bf187ae8ff9)

**Comment by basvanbemmel** [comment]
[log_20231007_83553.txt](https://github.com/ObjectVision/RSopen/files/12842996/log_20231007_83553.txt)
hierbij  de (laatste) log ook unknown meldingen e.d.

**Comment by basvanbemmel** [comment]
@Jip: Ik begrijp eigenlijk niet zo goed waarom dit zoveel kan afwijken tov RVNL / RSLight2021_ontwikkel_3, de kern van het model is toch niet gewijzigd? De "enige wijziging" buiten opschoning is toch privdata plancap verwijderd en utiliteit op basis van openbare bronnen. Mocht je er niet uitkomen dan kun je ook de eerste afsplitsing van RSOPen pakken en dan telkens de middelste versie nemen tov de huidge versie. Vervolgens resultaten bekijken en vervolgens weer middelen etc, tot je de versie hebt waarin ineens veel minder wordt gealloceerd. Kan tijdsintensief zijn maar met een snelle machine wel te doen. Laat maar weten of je hulp nodig hebt.

**Comment by jipclaassens** [comment]
Nou er is wel veel meer veranderd dan dat:
- plan capaciteit, en daarmee is de zeef ook flink aangepast
- er is veel herschreven aan classificaties (wat niet tot aanpassingen zou moeten leiden)
- de meeste regio indelingen zijn aangepast (zou ook niet tot aanpassingen moeten leiden)
- nieuwe operatoren, e.g. sub_or_null, fencecontainer, null_f  (idem)
- argmax ipv switchcase in de bag_nieuwbouw sector_rel
- alle ontkoppelde .fss'en eruit
- het iter mechanisme is generieker geworden

Verder ben ik inmiddels weer aardig terug bij de oude versie hoor!

**Comment by basvanbemmel** [comment]
ok dank voor de uitleg.

Grootste kanshebber uit het lijstje mijn inziens: "het iter mechanisme is generieker geworden". Wellicht is daar toch iets meer gewijzigd dan de bedoeling of is de werking toch anders dan verwacht.

**Comment by jipclaassens** [comment]
De resultaten ow3 bau zp kloppen totaal niet. Als ik naar de claim realisatie kijken zijn de RSopen bau resultaten die jij hebt en wat ik nu ook heb dichtbij de 100% claim realisatie en soms er al overheen. Oftewel die enorme resultaten uit BAU ZP kloppen totaal niet. 

Dus, we zitten nu juist beter!

**Comment by basvanbemmel** [comment]
Maar de enorme resultaten zaten ook in BAU 2050 voor het RV-prj, zie onder. niet alleen BAUZP. 

![BAU_BAUZP_2050_RV](https://github.com/ObjectVision/RSopen/assets/24241780/4e34ec9e-1ba3-4f00-af77-3c12bb212927)

**Comment by basvanbemmel** [comment]
Daarnaast je kunt wel 100% claimrealisatie hebben maar ik zou graag de absolute claim die erin gaat willen vergelijken tussen RSOpen en RVNL
