### ISSUE TITLE
NVM regio's synchroon laten lopen met COROP/Prov

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#70]

**Comment by basvanbemmel** [comment]
rood nieuwe begrenzing NVM

![Uploading image.png…]()

**Comment by jipclaassens** [comment]
Ziet er goed uit, hoe heb je dit gedaan? Heeft QGIS hiervoor een tooltje?

**Comment by basvanbemmel** [comment]
Source = "ArcGIS 10.8.1 bewerking 15 april 2024
						  "Stap 1: feature to point LMS_2011_versie_2012_12_13.shp inside"
						  "Stap 2: stap2_SJ_NVM_LMS_2011_versie_2012_12_13_feature_to_point_centroid.shp Spatial Join nvm_2011.shp"
						  "Stap 3: join --> stap3_LMS_2011_versie_2012_12_13_join_stap2_fid_fidnvm.shp"
						  "Stap 4: stap4_dissolve_nvmregio.shp dissolve op nvmregio"
						  "Stap 5: handmatig toekennen LMS-subzones aan een nvm-regio binnen een COROP-begrenzing"
						  "Stap 6: dissolve subzones met de nieuwe toekenning"
						  "Stap 7: dissolve met hulp=1, 1 grote polygoon"
						  "Stap 8: erase nvm_2011.shp met stap7"
						  "Stap 9: merge stap 8 en stap 6"
						  "Stap 9: dissolve stap 8 met nvmregio" 
						  "Stap 10: Multipart to Single Part stap 9" 
						  "Stap 11: Samenvoegen polygonen o.a. bij IJmuiden, Noord-Noord-Holland kust" 
						  "Stap 12: dissolve stap 11 met nvmregio" 


stap 5 is het belangrijkst.
Een paar uur mee bezig geweest
