### ISSUE TITLE
Restricties naar zeerhard/hard/middel/zacht omschrijven, geen varianten

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#75]

**Comment by jipclaassens** [comment]
De stap voor de selectie van PRV lagen is nu handmatig in Excel, dit moet toch handiger kunnen?

/SourceData/Beleid/OmgRecht/PRV/Fryslân/NL_IMRO_9921_PVR2014FryslanGC_GC03_Besluitvlak_P/Read_NLIMRO_Selectiebestand

**Comment by basvanbemmel** [comment]
excel? csv bedoel je, kan ook met een editor worden geopend. Nee is juist heel handig gebleken. Zou ik zo laten

**Comment by jipclaassens** [comment]
ja, of editor idd.

Maar, deze instellingen kunnen we niet vastleggen in de ontkoppelde tifs. Dat is wel een probleem...

**Comment by jipclaassens** [comment]
Add file dat to csv-files and in model/export parameters
