### ISSUE TITLE
PlanCapaciteit naar aparte repo

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#76]
- per zichtjaar
- per subsector
- hard/zacht

kopie van PM24

**Comment by BartRijken** [comment]
test

**Comment by jipclaassens** [comment]
Vragen Bas:
- cap: Gemeente Den Haag, geen shx
- cap: Wat is de bedoeling met Noord Brabant
- BP: enkelbestemming, wat is de bedoeling?

**Comment by jipclaassens** [comment]
Kunnen er harde EN zachte plekken op dezelfde locatie zijn?

![Image](https://github.com/user-attachments/assets/59b23cc5-9ffc-4286-b58d-89d1a2efee1a)

**Comment by jipclaassens** [comment]
To do, nog opdelen in priv en niet priv en dat weggschrijven.

**Comment by jipclaassens** [comment]
@basvanbemmel @IsmayPBL 
- Wat te doen met de plancap van NoordBrabant? Deze heeft nu geen eigen geometry?
