### ISSUE TITLE
Laatste svn-commit (10249) van Bart in RSOpen (toevoeging van diverse broninfo) overhevelen naar GIT

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/RSopen#8]

**Comment by basvanbemmel** [comment]
SHA-1: 0addfa569dbcd434bd716dee5a838485f8bc4115

* doorvoeren svn commit: 10249
behalve Basisjaar.dms, was al doorgevoerd
inhoudelijke wijziging!: MaxDichtheidInZeerMooiLandschap  van 150 --> 50 (VariantK.dms)
