### ISSUE TITLE
SourceData en rekenregels t.a.v. WBS mergen van WLO cfg naar RSOpen (Bas) en RVFriesland (Jip)

### ISSUE THREAD

**Issue by BartRijken** [ObjectVision/RSopen#80]
Specifieke vragen @basvanbemmel :

De WBS-variant die als het goed is in de WLO-configuratie is ingebouwd (obv kaarten van de afdeling van Wieke Tas (DGWB)).
a.	Is dit idd ingebouwd?
b.	Wat is de status van de kaarten die zijn ingebouwd (definitief of concept)?
c.	In het laatste geval (concept): zijn jullie nog van plan de definitieve in te bouwen? Wanneer?
d.	Kan Jip dit alles (tzt)  mergen naar de nieuwe, op RSOpen gebaseerde, Deltares configuratie (RVFriesland)?

**Comment by basvanbemmel** [comment]
a) dat is ingebouwd ja, het gaat om een aanlevering van Directoraat-generaal Water en Bodem, Afdeling klimaatadaptatie, Ministerie van Infrastructuur en Waterstaat op 16 april 2024 per email Ruimtelijk afwegingskader kaarten.zip. Alleen de eindkaart is ingebouwd (de zogenaamde combinatiekaart dus, niet alle tussenliggende kaarten van het afwegingskader). 

lokatie in WLO2024-cfg (versie 11010):
/SourceData/Water/WBS/Combinatiekaart
/SourceData/Water/WBS/KlasseD/geometry (vector voor klasse D)
de zelf gecombineerde kaart staat onder /SourceData/Water/WBS/Combinatiekaart_5mtr (mtr resolutie dus)
Vervolgens naar 25mtr gehaald dmv item: /SourceData/Water/WBS/Combinatiekaart_25mtr
Aantal klassen teruggebracht onder item: /SourceData/Water/WBS/Combinatiekaart_6kl_25mtr (6 klassen ipv 8)

b) we hebben 3 aanleveringen gehad maar dit is echt de defintieve. Belangrijk is dat de Waddenzee niet meer in de kaart zit (niet bouwen)

c) nbt

d) Jip? kwestie van WBS.dms kopieren en includen lijkt mij.
