### ISSUE TITLE
RS configuraties met landbouw daarin vinden, op OVSRV09 zetten en draaiend krijgen (suitability maps en landuse baseyear)

### ISSUE THREAD

**Issue by BartRijken** [ObjectVision/RSopen#91]
Dus van:

- [ ] https://pbl.sliksvn.com/ruimtescanner/PBL/Oplevering/Delta_Scenarios_2017_2_TUcleaned
- [ ] https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/PeatyMeadows_Stripped

Naar: C:\ProjDir_Bart

**Comment by BartRijken** [comment]
@jipclaassens kan jij C:\ProjDir_Jip\_Archief\Delta_Scenarios_2017_2_TUcleaned draaiend maken? Iig de suitability maps?

**Comment by jipclaassens** [comment]
/Zichtjaren/Scenarios/Fixation_NoDD/RunPeriods/Y2010_Y2010/d_alloc/landuse_grid

status flag == false, waarom?
