### ISSUE TITLE
Vervang de opbrengstendervingskaarten o.b.v. de HELP systematiek voor zover en waar mogelijk door de opbrengstenderving uit de WaterWijzerLandbouw

### ISSUE THREAD

**Issue by BartRijken** [ObjectVision/RSopen#95]
WaterWijzerLandbouw: https://waterwijzerlandbouw.wur.nl/

**Comment by BartRijken** [comment]
Contactpersoon bij Deltares (CC naar Bart Rijken): Janneke Pouwels: janneke.pouwels@deltares.nl

**Comment by jipclaassens** [comment]
@BartRijken nu zijn alle kaarten die Janneke aangeleverd via een ModelParameter te gebruiken. Voor de gewassen die niet in de levering zitten wordt nu wel de HELP-systematiek gebruikt.

**Comment by BartRijken** [comment]
> @BartRijken nu zijn alle kaarten die Janneke aangeleverd via een ModelParameter te gebruiken. Voor de gewassen die niet in de levering zitten wordt nu wel de HELP-systematiek gebruikt.

Top. Als het goed is heeft Janneke opbrengstenderving gekleverd voor 2 scenario's: BAU en WBS. Klopt dat? Heb je dat ook geparametriseerd? Dat zou voor nu even voldoende zijn. Wel graag beide varianten inlezen.

**Comment by jipclaassens** [comment]
> > @BartRijken nu zijn alle kaarten die Janneke aangeleverd via een ModelParameter te gebruiken. Voor de gewassen die niet in de levering zitten wordt nu wel de HELP-systematiek gebruikt.
> 
> Top. Als het goed is heeft Janneke opbrengstenderving gekleverd voor 2 scenario's: BAU en WBS. Klopt dat? Heb je dat ook geparametriseerd? Dat zou voor nu even voldoende zijn. Wel graag beide varianten inlezen.

Ja, zo zit het erin.
