### ISSUE TITLE
Omgevingsscenario's en beleidsvarianten beschrijven in de RV Friesland cfg  

### ISSUE THREAD

**Issue by BartRijken** [ObjectVision/RSopen#97]

**Comment by jipclaassens** [comment]
Hoe relateert dit aan #112

**Comment by BartRijken** [comment]
> Hoe relateert dit aan #112

Dit is hetzelfde. Ik houd dit issue open en zet #112 dicht

**Comment by jipclaassens** [comment]
@BartRijken is de minimale dichtheidstoename niet te laag? We zien nu woningen verschijnen in Oost-Groningen, met een dichtheid van 1woning extra... 

![Image](https://github.com/user-attachments/assets/d6c6e5e0-28b0-48e5-9814-619dcd20cb04)
